### ISSUE TITLE
[Eventbus Gateway] Apply the service account IAM role to the application

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#102388]
### Background
We have created an IAM role that can be used to assume the role that the eventbus gateway has created for us on their side. We need to apply this IAM role as a service account for our application so that it can assume that role.

#### Initial assumptions
**Note:** Turns out I was incorrect about everything below and there are not really 2 separate options, we need to do both things:

I'm still trying to determine the best way to do this. The 2 leading contenders I am looking at are:
1) Add a `serviceAccountName` to the `deployment.yaml` file
  * If this works, it will be quite simple. I'm not completely confident that this approach will actually accomplish what I want it to though
  * Docs: https://docs.aws.amazon.com/eks/latest/userguide/pod-configuration.html
2) Create a service-account.yaml file
  * I have an example from the `platform-atlas` application that I think might work, but I am having trouble finding documentation that explains how to configure this in an Argo application
  * Example from the `platform-atlas` app:
  ```yml
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
     argocd.argoproj.io/hook: PreSync
      argocd.argoproj.io/sync-wave: "-5"
      eks.amazonaws.com/role-arn: {role_arn}
    labels:
      app.kubernetes.io/component: {serviceAccountName}
      app.kubernetes.io/name: {serviceAccountName}
      app.kubernetes.io/part-of: {serviceAccountName}
    name: {serviceAccountName}
    namespace: {releaseNamespace}
  ```

#### 02/03/2025
1) I started by adding a line for the `serviceAccountName` to `deployment.yaml` in [this PR](department-of-veterans-affairs/vsp-infra-application-manifests/pull/3407) as it was mentioned in the AWS docs [here](https://docs.aws.amazon.com/eks/latest/userguide/pod-configuration.html).
2) This caused an error with the deployment, which was caused by a formatting issue (I put the `serviceAccountName` key and its value on separate lines on accident). [This PR](department-of-veterans-affairs/vsp-infra-application-manifests/pull/3409) fixes the issue
3) That fixed the deployment, but I started getting an error that the service account with name: `eventbus-gateway-service-account-sandbox` could not be found. This made me realize that I needed to create a Service Account object and that I could use the name that I assigned to that object in the `development.yaml` file. [This PR](department-of-veterans-affairs/vsp-infra-application-manifests/pull/3410) adds the new Service Account.
4) I'm not getting any errors currently, so I need to wait until the networking issues between the EKS dev cluster and Eventbus' staging environment are resolved. Then I can see about running a telnet (`telnet {bootstap server HOST} {bootstrap server PORT}` to see if I can get a connection established
