### ISSUE TITLE
[CST] Update Mock Data for submitting 5103 tracked items

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#102822]
### Bug
- Found that when you use mock data locally and attempt to submit a 5103 form it fails and returns the error `Betamocks default response requested but none exist. Please create one at: [../vets-api-mockdata/lighthouse/benefits_claims/submit_5103/default.yml].` 
- After invetigating found that to fix we need to create a new folder called `submit_5103` in `vets-api-mockdata/lighthouse/benefits_claims/` and add a default.yml folder with the following text:

```YML
---
:method: :post
:body:
:headers:
  date: Fri, 23 Dec 2022 00:13:02 GMT
  content-type: application/json; charset=utf-8
  connection: close
  x-ratelimit-remaining-minute: '59'
  x-ratelimit-limit-minute: '60'
  ratelimit-remaining: '59'
  ratelimit-limit: '60'
  ratelimit-reset: '4'
  etag: W/'76c5f17e592bf4cdf9f8f829d2f55b62'
  referrer-policy: strict-origin-when-cross-origin
  vary: Origin, Origin
  x-content-type-options: nosniff
  x-download-options: noopen
  x-frame-options: SAMEORIGIN
  x-git-sha: 05db452e3b89f62fe499d01aaaac45f96ce8c676
  x-github-repository: https://github.com/department-of-veterans-affairs/vets-api
  x-permitted-cross-domain-policies: none
  x-request-id: dbe14008-4060-4a6e-8501-042c02cd42d0
  x-runtime: '6.414054'
  x-xss-protection: 1; mode=block
  access-control-allow-origin: '*'
  x-kong-upstream-latency: '6421'
  x-kong-proxy-latency: '1'
  via: kong/2.3.2
  strict-transport-security: max-age=31536000; includeSubDomains; preload
  cache-control: no-cache, no-store
  pragma: no-cache
  transfer-encoding: chunked
:status: 200
```

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] Add default.yml file
- [ ] Add submit_5103 folder

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] You can locally submit a 5103 tracked item when using mocks
