### ISSUE TITLE
Fix Flaky Test Blocking CI: modules/ivc_champva/spec/services/attachments_spec.rb

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#104787]
## User Story
As a developer, I want to not hit flakey tests, so that I can develop faster.

## Issue Description
This spec has been intermittently failing, causing disruptions in the vets-api CI pipeline. The failure is inconsistent and does not appear to be related to recent changes, indicating that the test may be flaky. It's highly likely this is seen more frequently when tests run in parallel (which they do in CI). I was able to see a failure after running this three times locally (`bin/test modules/ivc_champva --parallel` or `bundle exec parallel_rspec modules/ivc_champva`).

The errors can be found in this [Code Check run](https://github.com/department-of-veterans-affairs/vets-api/runs/38501311773) and another one in this [Code Check run](https://github.com/department-of-veterans-affairs/vets-api/runs/39921741745). And [another one](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/14250143572/job/39940720825).

**The two tests below (and the ones linked above) have their file paths in common:** `tmp/_vha_10_10d_additional_applicants-1-stamped.pdf`. I think it has to do with a `uuid` being nil, because that's what should be at the beginning of the PDF name (see [pdf_filler.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/ivc_champva/app/services/ivc_champva/pdf_filler.rb#L23)). When it's nil, another test can also have the same path and it can be deleted (see [pdf_stamper.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/ivc_champva/app/services/ivc_champva/pdf_stamper.rb#L180)) when the tests run in parallel. 

Error:
```
An error occurred while verifying stamp: pdftk failed with command /usr/bin/pdftk /app/tmp/_vha_10_10d_additional_applicants-1-stamped.pdf multistamp tmp/269bd0a66b17a54640ba2750813fe1e6 output tmp/76a85612ae014be5cf5a302675153cab.pdf command output was: Error: Invalid PDF: Rebuild failed: trailer not found.; Original message: Unexpected end of file at file pointer 1005655 Error: Failed to open input PDF file:     /app/tmp/_vha_10_10d_additional_applicants-1-stamped.pdf Errors encountered.  No output created. Done.  Input errors, so no output created.
\e[1mFailure/Error: \e[0mfile_paths.concat form.handle_attachments('modules/ivc_champva/templates/vha_10_10d.pdf')

StandardError:
  An error occurred while verifying stamp: pdftk failed with command
  /usr/bin/pdftk /app/tmp/_vha_10_10d_additional_applicants-1-stamped.pdf multistamp tmp/269bd0a66b17a54640ba2750813fe1e6 output tmp/76a85612ae014be5cf5a302675153cab.pdf
  command output was:
  Error: Invalid PDF: Rebuild failed: trailer not found.; Original message: Unexpected end of file at file pointer 1005655
  Error: Failed to open input PDF file: 
     /app/tmp/_vha_10_10d_additional_applicants-1-stamped.pdf
  Errors encountered.  No output created.
  Done.  Input errors, so no output created.
```
While trying to debug this locally, I also hit this error:
```
  1) IvcChampva::Attachments#handle_attachments when there are multiple PDFs needed generates an additional pdf for 10-10D
     Failure/Error: file_paths = form.handle_attachments('modules/ivc_champva/templates/vha_10_10d.pdf')

     StandardError:
       An error occurred while verifying stamp: No such file or directory @ apply2files - /Users/rebeccatolmach/git/vets-api/tmp/_vha_10_10d_additional_applicants-1-stamped.pdf
     # ./modules/ivc_champva/app/services/ivc_champva/pdf_stamper.rb:222:in `rescue in verify'
     # ./modules/ivc_champva/app/services/ivc_champva/pdf_stamper.rb:211:in `verify'
     # ./modules/ivc_champva/app/services/ivc_champva/pdf_stamper.rb:228:in `verified_multistamp'
     # ./modules/ivc_champva/app/services/ivc_champva/pdf_stamper.rb:148:in `stamp'
     # ./modules/ivc_champva/app/services/ivc_champva/pdf_stamper.rb:69:in `block in stamp_signature'
     # ./modules/ivc_champva/app/services/ivc_champva/pdf_stamper.rb:68:in `each'
     # ./modules/ivc_champva/app/services/ivc_champva/pdf_stamper.rb:68:in `stamp_signature'
     # ./modules/ivc_champva/app/services/ivc_champva/pdf_stamper.rb:22:in `stamp_pdf'
     # ./modules/ivc_champva/app/services/ivc_champva/pdf_filler.rb:31:in `generate'
     # ./modules/ivc_champva/app/services/ivc_champva/attachments.rb:93:in `generate_additional_pdf'
     # ./modules/ivc_champva/app/services/ivc_champva/attachments.rb:65:in `block in get_attachments'
     # ./modules/ivc_champva/app/services/ivc_champva/attachments.rb:64:in `each'
     # ./modules/ivc_champva/app/services/ivc_champva/attachments.rb:64:in `each_slice'
     # ./modules/ivc_champva/app/services/ivc_champva/attachments.rb:64:in `with_index'
     # ./modules/ivc_champva/app/services/ivc_champva/attachments.rb:64:in `get_attachments'
     # ./modules/ivc_champva/app/services/ivc_champva/attachments.rb:12:in `handle_attachments'
     # ./modules/ivc_champva/spec/services/attachments_spec.rb:47:in `block (4 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Errno::ENOENT:
     #   No such file or directory @ apply2files - /Users/rebeccatolmach/git/vets-api/tmp/_vha_10_10d_additional_applicants-1-stamped.pdf
     #   ./modules/ivc_champva/app/services/ivc_champva/pdf_stamper.rb:180:in `delete'
```

## Tasks
- [ ]  Investigate the root cause of flakiness.
- [ ] Improve test stability by adjusting timeouts, mocking dependencies, or refining assertions.
- [ ] Run the test multiple times in parallel to verify stability before merging the fix.

## Acceptance Criteria
- [ ] Spec is consistently passing.
- [ ] Changes to this spec do not trigger other flaky tests
