### ISSUE TITLE
[CST] [Prototype] Stabilize the list‑level spinner with a fixed‑height placeholder

### ISSUE THREAD

**Issue by MikeC-A6** [department-of-veterans-affairs/va.gov-team#107787]
### User Story – Prevent layout jumps while the claim list is loading
As a **veteran waiting for my claims and appeals list to load**,  
I want the rest of the page to stay perfectly still,  
so the interface doesn’t jump up or down while the list spinner appears and disappears.

### Reference implementation (My VA Dashboard)
My VA solves this with widget‑level placeholders that reserve consistent space:

* **`LoadingWidgetPlaceholder.jsx`**  
  <https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/LoadingWidgetPlaceholder.jsx>  
  – renders a fixed‑height gray card while health‑care / disability‑rating widgets load.
* **`Dashboard.scss`** sets explicit `min-height` on each widget region to eliminate CLS.

We’ll copy that idea—use a fixed‑height wrapper so our list spinner can’t collapse the layout.

---

## Tasks
- [ ] **Add CSS placeholder class**

      ```css
      /* claims-list-placeholder.scss */
      .claims-list-placeholder {
        min-height: 480px;      /* ≈ four claim cards */
        display: flex;
        align-items: center;
        justify-content: center;
      }

      @media (max-width: 480px) {
        .claims-list-placeholder {
          min-height: 560px;
        }
      }
      ```

      > *Reference: `dashboard-widget-wrapper` in Dashboard stylesheet.*

- [ ] **Wrap the primary list loader**

      ```diff
      // YourClaimsPageV2.jsx  (lines 260‑270)
      {listLoading && listIsEmpty && (
      -  <va-loading-indicator message="Loading your claims and appeals…" />
      +  <div className="claims-list-placeholder" aria-busy="true">
      +    <va-loading-indicator message="Loading your claims and appeals…" />
      +  </div>
      )}
      ```

- [ ] **Remove any margin utility classes** (`vads-u-margin-y--4` etc.) on that branch to keep height consistent once rows render.
- [ ] **Unit / e2e tests**
  * RTL snapshot should include `.claims-list-placeholder`.  
  * Cypress: stub list API delay and assert placeholder exists, then disappears without CLS.

### Acceptance Criteria
* While `listLoading && listIsEmpty` is `true`, list area reserves ≥ 480 px and centers the spinner.  
* When data arrives, the placeholder swaps to rows with **no cumulative layout shift > 0.02** (Lighthouse CLS metric).  
* Other page sections do not move vertically during the transition.  
* Placeholder carries `aria-busy="true"`, satisfying axe‑core.  
* All unit, e2e, and Lighthouse tests pass.

---

**Design parity:** Mimics My VA Dashboard’s stable widget placeholders without introducing full skeleton loaders.
