### ISSUE TITLE
[COLOR CONTRAST]: Subway map numbers do not meet 4.5:1 ratio for contrast

### ISSUE THREAD

**Issue by peterhill-oddball** [department-of-veterans-affairs/va.gov-team#1079]
Migrated from vets.gov issue [15626](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15626)

## Issue
The subway map numbers have a contrast ratio below the required 4.5:1 to meet WCAG2 Level AA compliance. axe-core does not alert on these because they are CSS `::before` declarations, but a manual test reveals the working contrast ratio is **3.272**. Screenshot attached below.

## Acceptance Criteria
As a user, I want the color contrast ratio to be at least 4.5:1 for the white text on gray background in the subway map numbers. Any of the following tools can be used to verify contrast ratio:

* https://snook.ca/technical/colour_contrast/colour.html
* https://contrast-ratio.com/
* http://contrast-finder.tanaguru.com/

## Environment

* MacOS Mojave
* Chrome latest
* https://staging.va.gov/education/submit-school-feedback/introduction

## Possible Fixes (optional)
```css
.process-step:before {
  ...
  background: #849097;
  /* Could be changed to #70787C or #6B797F and meet the required 4.5:1 ratio */
  ...
}
```
---
![screen shot 2018-12-11 at 8 43 50 am](https://user-images.githubusercontent.com/934879/49808647-a85a3680-fd22-11e8-92ec-dbe6f2e36538.png)
