### ISSUE TITLE
Add Exclamation Point issue to Settings Troubleshooting

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#109013]
## User Story
As an engineer, I want to know yaml tags issue, so that troubleshoot settings.

## Issue Description
- Yaml uses ! for tags, so if a Parameter starts with a ! then it will be a nil Settings value

```yaml
# bad 
example_settings: !value 

# good 
example_settings: "!value" 
```

The recommended resolution with ENVs is to use `.dump`

```ruby
example_settings: <%= ENV['example_settings']&.dump %>
```

## Tasks
- [x] Add the yaml tag issue to troubleshooting section of the Settings documentation on Platform docs

## Acceptance Criteria
- [x] page is published
