### ISSUE TITLE
Clean Up Unused Ignored Columns & Add Unique Index for email in TudAccount

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#110525]
## User Story
As a backend engineer, I want to clean up unused columns, so that outdated columns are not ignored.

## Issue Description
The TestUserDashboard::TudAccount model currently triggers several RuboCop offenses:

**Unused Ignored Columns:**
The following columns are listed in ignored_columns but do not exist in the tud_accounts table:
- standard
- available
- account_type
- id_type
Offense: Rails/UnusedIgnoredColumns

**Missing Unique Index for Email:**
- The model validates uniqueness of email but lacks a corresponding unique index in the database.
- Offense: Rails/UniqueValidationWithoutIndex

## Tasks
- [ ]  Remove the following lines from rubocop.yml:
```
Rails/UnusedIgnoredColumns:
  Exclude:
    - 'modules/test_user_dashboard/app/models/test_user_dashboard/tud_account.rb'

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'modules/test_user_dashboard/app/models/test_user_dashboard/tud_account.rb'

```
- [ ]  Remove standard, available, account_type, and id_type from self.ignored_columns.
- [ ]  Verify the current schema to confirm those columns are no longer present.
- [ ]  Create and run a Rails migration to add a unique index on email in the tud_accounts table:
```
class AddUniqueIndexToTudAccountsEmail < ActiveRecord::Migration[6.1]
  def change
    add_index :tud_accounts, :email, unique: true
  end
end
```

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome(s)._
