### ISSUE TITLE
Add additional detail to the Downtime Notification window instructions

### ISSUE THREAD

**Issue by gracexu94** [department-of-veterans-affairs/va.gov-team#112300]
### Description

Our team recently implemented this component using the excellent instructions provided. I wanted to share the following steps we used as a team in case they might be useful to others: 

----------
To test your implementation locally, you can do the following after pulling the latest version of `vets-api` with your config changes ([example config setup PR here](https://github.com/department-of-veterans-affairs/vets-api/pull/22695)):
1. Set up a test maintenance window in the PagerDuty service you configured
2. Update your vets-api `settings.local.yml` file to include the following (you can get the PagerDuty API token from Argo vets-api-staging's Rails console)
```
maintenance:
  pagerduty_api_token: <api token from Argo>
  services:
    decision_reviews: <7-char staging pagerduty service id, usually starting with P> -- this ID can be found in the URL of your PagerDuty service 
```
3. With vets-api running locally, open a rails console and use the following commands to test:
```
MaintenanceWindow.count # should return 0 -- your downtime notification window should not be displaying
PagerDuty::PollMaintenanceWindows.perform_async # should return an ID, and you should see the Sidekiq job success logs
MaintenanceWindow.count # should be > 0 now
```

4.  Confirm that the API endpoint is returning the expected maintenance windows by accessing [http://localhost:3000/v0/maintenance_windows](http://localhost:3000/v0/maintenance_windows). 
5. The downtime notification window should now be displaying on your local instance of the app
You can update the staging maintenance windows in PagerDuty to test different scenarios.

### Timeline/Deadline to Publish
N/A

### Is this in support of an OCTO OKR or larger initiative? (please indicate)
N/A

### Which type of team are you on? (Platform team, VFS team, or Leadership)

VFS team

### Which portfolio is your team on? (Benefits, Health, Digital Experience)
Benefits
