### ISSUE TITLE
[Spike] Formulate strategy for accessing appointments data via MAP in dev/staging/production environments

### ISSUE THREAD

**Issue by massrb** [department-of-veterans-affairs/va.gov-team#13834]
How can access to the MAP sandbox be accomplished in the staged environment or in a draft PR through the health quest service ? 

This ticket is related to administration and has no related coding requirements or that should be very minimal if anything

The Health Quest Service uses a similar configuration in settings as VAOS does. Here is what VAOS looks like. As you can see, in the dev environment there is nothing there because VAOS in Dev has no connection whatsoever: 

```
va_mobile:
  url: 'https://veteran.apps.va.gov'
  mock: false
  key_path: /fake/client/key/path
  timeout: 15
```

The Health Quest has the same type of configuration derived from how VAOS does this, but the release process for staging and production would need to take this into account or would need to know about it. This example shows the use of a locally stored private key to access the sandbox

```
hqva_mobile:
  url: 'https://veteran.apps.va.gov'
  mock: false
  # key_path: /fake/client/key/path
  key_path: /Users/laurenceguild/my-play-certs/sandbox_rsa
  timeout: 15
```

## Tasks
- [ ] Determine how can we access the sandbox in each environment for staging/dev
- [ ] Determine if the requirements have changed because of the need to use getCare API
- [ ] Determine what the release process needs to add

## Acceptance Criteria
- [ ] Document findings
