### ISSUE TITLE
Create devops configurations for MAP and Lighthouse in the staging and development environments

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#18661]
Add MAP and Lighthouse configurations to the `staging-settings.local.yml.j2` and `dev-settings.local.yml.j2` files so that vets-api can ultimately obtain tokens and create/get resources from the MAP and Lighthouse services.

Staging example:
```
hqva_mobile:
  key_path: /srv/vets-api/secret/health-quest.key
  timeout: 30
  URL: <staging-url>
  lighthouse:
    URL: <staging-url>
    host: <staging-url>
    key_path: <staging-key-path>
```
