### ISSUE TITLE
Move test configuration into the test.yml settings file.

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#18676]
Add the following configuration into the `config/settings/test.yml` file so that we're not checking for configuration settings by the current environment in the lighthouse service module code.

```
hqva_mobile:
  url: "https://veteran.apps.va.gov"
  mock: false
  key_path: <key>
  development_key_path: <key>
  timeout: 15
  lighthouse:
    url: "https://sandbox-api.va.gov"
    host: "sandbox-api.va.gov"
    aud_claim_url: <aud_url>
    claim_common_id: <id>
    redis_session_prefix: "healthquest_lighthouse"
    mock: false
    key_path: <key>
```
