### ISSUE TITLE
[QA-internal] Research Cypress CI-only tests isolation

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#21365]
Investigate possibility & feasibility of isolating a CI-only subset of Cypress tests, so that CI deploys can be made faster.

## Problem statement

VSP recently said "CI deploys are taking too long," citing one of the reasons as too many Cypress automated tests running.  Former VSA Engineering Lead also commented that our "Testing Triangle" is "upside-down".

**Comment by tlei123** [comment]
Cypress can run a subset of test-files via the **--spec** option, either by folder or by filename-extension in the specified glob-pattern:
- `cypress run --spec **/tests/e2e/ci/*.cypress.spec.js?(x)`
- `cypress run --spec **/tests/e2e/*.ci.cypress.spec.js?(x)`

We can specify CI-only test-files by either moving them to a subfolder or adding dot-extension segment to the filenames.

**Comment by tlei123** [comment]
Per practice-leads Nick Sullivan & Anna Carey, we also need to have a scheduled run in CI that does run ALL tests, rather than rely on engineers to run them locally.

**Comment by tlei123** [comment]
[To be tested] According to CircleCI docs, we can add a separate, [scheduled CircleCI workflow](https://circleci.com/docs/2.0/workflows/?section=pipelines#scheduling-a-workflow) for running all tests.  It must be separate, so that existing commit-triggered workflows continue to work.

With this implemented, we can then modify the commit-triggered workflows to run a subset of tests.

**Comment by tlei123** [comment]
Cypress & CircleCI configs-testing with my side-project test-branch ('test/circleci-scheduled-workflow`) is going well:
- Cypress configs:
  - default cypress.json config now modified to run a subset of tests (moved into a subfolder):
    ```
    {
      ...
      "testFiles":: "**/smoke/*.spec.js",
      ...
    {
    ```
  - new cypress-all.json config runs all tests:
    ```
    {
      ...
      "testFiles":: "**/*.spec.js",
      ...
    {
    ```
- CircleCI config:
  - Default repo-push-triggered workflow remains unchanged [and retains deploy job after `cypress/run`:
    ```
    workflows:
      test_branch_push_triggered:
        when:
          equal: [ test/circleci-scheduled-workflow, << pipeline.git.branch >> ]
        jobs:
          - cypress/run:
              start: npm start
              ...
          - deploy-to-dev:
              ...
    ```
  - New scheduled workflow uses schedule-trigger instead [running every morning at 6am UTC], and specifies `cypress-all.json` config-file:
    ```
    workflows:
      ...
      test_branch_scheduled:
        triggers:
          - schedule:
              cron: 0 6 * * *
              filters:
                branches:
                  only:
                    - test/circleci-scheduled-workflow
        jobs:
          - cypress/run:
              config-file: cypress-all.json
              start: npm start
              ...
    ```
    deploy job can optionally be deleted from scheduled workflow.
- CircleCI pipeline run results:
    ![cypress-circleci-poc-results](https://user-images.githubusercontent.com/587583/111021482-d7d8cd00-8389-11eb-9f06-5dcd49fa7e40.png)


Will test Cypress configs using filename-dot-segment differences next.

**Comment by tlei123** [comment]
### Proof of Concept (cont.d)

Cypress & CircleCI configs-testing with my side-project test-branch successful also with separation by filename-dot-segment.

#### Tests separation by filename-dot-segment:

- CircleCI pipeline runs:
    ![cy-ci-pipeline-2](https://user-images.githubusercontent.com/587583/111116115-c70f8f00-8522-11eb-9da0-4d7f596b5432.png)
  - **test_scheduled** workflow test results (**all** tests):
    ![cy-ci-pipeline2-test-result-scheduled](https://user-images.githubusercontent.com/587583/111116161-d8589b80-8522-11eb-8792-e47e658e7ade.png)
  - **test_push_triggered** workflow test results (**subset** of tests):
    ![cy-ci-pipeline2-test-result-push-triggered](https://user-images.githubusercontent.com/587583/111116184-e3133080-8522-11eb-8f8b-a9d2f0ec4baf.png)

- Cypress configs:
  - new **cypress-all.json** config runs **all tests** for **scheduled** CircleCI workflow:
    ```
    {
      ...
      "testFiles":: "**/*.spec.js",
      ...
    {
    ```
  - default **cypress.json** config modified to run a **subset of tests** (with **filename-dot-segment**) for default **push-triggered** workflow:
    ```
    {
      ...
      "testFiles":: "**/*.smoke.spec.js",
      ...
    {
    ```
- CircleCI config:
  - New **scheduled workflow** uses schedule-trigger, specifying **cypress-all.json** config-file:
    ```
    workflows:
      ...
      test_scheduled:
        triggers:
          - schedule:
              cron: 0 6 * * *
              filters:
                branches:
                  only:
                    - test/cy-ci-workflows-2
        jobs:
          - cypress/run:
              config-file: cypress-all.json
              start: npm start
              ...
    ```
  - Default **push-triggered workflow** remains unchanged, implicitly using default, modified **cypress.json** config-file:
    ```
    workflows:
      test_push_triggered:
        when:
          equal: [ test/cy-ci-workflows-2, << pipeline.git.branch >> ]
        jobs:
          - cypress/run:
              start: npm star
              ...
          ...
    ```


Will test Cypress configs using filename-dot-segment differences next.

**Comment by tlei123** [comment]
Started experimenting CirceCI-Slack integration, using [circleci/slack@4.3.1 Orb](https://circleci.com/developer/orbs/orb/circleci/slack#usage-notify_on_fail_with_template).

### CircleCI config:

Initial custom-notification added to **test/cy-ci-workflows-1** branch, triggering in **test_push_triggered** workflow for testing purposes.  Once notification config is matured, will move to scheduled workflow:
```
orbs:
  cypress: cypress-io/cypress@1
  slack: circleci/slack@4.3.1
```
```
jobs:
  ...
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "Text notification (custom)",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
```
```
workflows:
  test_push_triggered:
    when:
      equal: [ test/cy-ci-workflows-1, << pipeline.git.branch >> ]
    jobs:
      - cypress/run:
          ...
      - notify:
          context: Slack
```

### Slack experimental workspace & app

Created **AdHoc-VSA-QA-experimental** temporary Slack-workspace and **VSA-QA-CircleCI** Slack-app to test CircleCI-notifications.  Initial Slack-custom-notification worked:
![circleci-slack-custom-notification](https://user-images.githubusercontent.com/587583/112767798-92451280-8fcd-11eb-89e9-9e914ef7bf32.png)

**Comment by tlei123** [comment]
### Cypress config
Deleted previous notify job.  Added Slack-notification steps into cypress/run job, so as to trigger by pass/fail test-results.
```
workflows:
  test_push_triggered:
    when:
      equal: [ test/cy-ci-workflows-1, << pipeline.git.branch >> ]
    jobs:
      - cypress/run:
          context: Slack
          ...
          post-steps:
            - slack/notify:
                event: pass
                mentions: '@here'
                template: 'basic_success_1'
            - slack/notify:
                event: fail
                mentions: '@here'
                template: 'basic_fail_1'
            ...
```

### Slack pass & fail notifications
![circleci-slack-pass-fail-notifications](https://user-images.githubusercontent.com/587583/112773278-3b9a0180-8fea-11eb-8f6f-3e0e6982c6b1.png)

**Comment by tlei123** [comment]
Now that Slack-notifications are working, deleted notification steps from test_push-triggered workflow, and added **fail-only notification-step** to **test_scheduled** workflow -- scheduled to run at 6am UTC.

Will check Slack tmrw morning.

### Cypress config
```
workflows:
  test_push_triggered:
    when:
      ...
    jobs:
      - cypress/run:
          ...
          post-steps:
           ...
  test_scheduled:
    triggers:
      ...
    jobs:
      - cypress/run:
          context: Slack
          ...
          post-steps:
            - slack/notify:
                event: fail
                mentions: '@here'
                template: 'basic_fail_1'
            ...
```

**Comment by tlei123** [comment]
Just checked Slack, and **test_scheduled** workflow's fail-only Slack-notification worked. [See screenshot of Slack-message from last night's scheduled-run.]
<img width="600" alt="slack-notification-scehduled-workflow-210329" src="https://user-images.githubusercontent.com/587583/112872729-9167bb80-9075-11eb-82b6-c97953e9adfa.png">

**Comment by tlei123** [comment]
FYI, now that we know CircleCI-Slack integration's working, I changed test_scheduled workflow chrontabs in both test-branches to weekly, to avoid exhausting my CircleCI free-tier monthly credits.

**Comment by tlei123** [comment]
**test_scheduled** workflow's fail-only Slack-notification for updated weekly (Mondays 7am UTC):
![slack-msg-test-scheduled-fail-210405](https://user-images.githubusercontent.com/587583/113668804-a345f180-9667-11eb-8204-2652a8d8812c.png)

**Comment by tlei123** [comment]
In addition to PR-/push-triggered and scheduled test-runs, Backend Practice Lead Anna Carey would like to add a "deploy-triggered" run to run all tests for the daily deploys.

Research Jenkins pipelines to determine how this can be done.  DevOps is planning to migrate deployments to CircleCI, but actual implementation timeline's unknown.

**Comment by tlei123** [comment]
Well, DevOps migrated from CircleCI to GitHub Actions for triggering Cypress tests.  Need to start research GitHub Actions.

Fortunately, Cypress does have a [GitHub-Action module](https://github.com/cypress-io/github-action), so it should hopefully be straightforward to replicate test-isolation configs.

**Comment by tlei123** [comment]
Created two "foobar" GH Actions in side-project, one push-triggered and the other release-triggered.  Both are working.

Need to continue research into the Actions' Cypress config settings, as well as how exactly vets-website's Actions are triggered in CI/CD.

**Comment by tlei123** [comment]
Updated GH Actions now with actual Node/NPM/Cypress steps, using [Cypress github-action](https://github.com/cypress-io/github-action) and [actions/setup-node](https://github.com/actions/setup-node) modules.  Both are working.

### Push-triggered action:
- Triggered by code **pushes**
- Specific to **develop** branch
- Runs only test-files in special **subfolder**

**./github/workflows/demo-push-triggered.yml**:
```yaml
name: Demo push-triggered
on:
  push:
    branches: ["develop"]
jobs:
  Demo-push-triggered-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "13"
      - name: Install NPM packages
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run start
          wait-on: "http://localhost:4200"
          wait-on-timeout: 120
          browser: chrome
          headless: true
          spec: cypress/integration/always/**/*.spec.js
```

### Release-triggered action:
- Triggered by **releases**
- Specific to **master** branch
- Runs **all** test-files.

**./github/workflows/demo-push-triggered.yml**:
```yaml
name: Demo release-triggered
on:
  release:
    branches: ["master"]
jobs:
  Demo-release-triggered-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "13"
      - name: Install NPM packages
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run start
          wait-on: "http://localhost:4200"
          wait-on-timeout: 120
          browser: chrome
          headless: true
          spec: cypress/integration/**/*.spec.js
```

### Side-project Actions page:
![image](https://user-images.githubusercontent.com/587583/122857305-1fe28680-d2cd-11eb-8239-b93c40afe397.png)
