### ISSUE TITLE
Configure 10-10CG submissions for MuleSoft

### ISSUE THREAD

**Issue by jchilders** [department-of-veterans-affairs/va.gov-team#34690]
## Description
Add/change configuration for 10-10CG to add MuleSoft configuration

## Background/context 
Currently on va.gov 10-10CG data is submitted to the CARMA team via Salesforce. The CARMA team is putting MuleSoft in front of Salesforce, and we need to configure vets-api accordingly.

Please see [epic 31307](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31307) for full context.

Igor Khurgin (igor.khurgin@salesforce.com) is the technical contact with the CARMA group, and the primary Mulesoft technical contact.

Kevin Musiorski (kevin.musiorski@govcio.com) is the primary vets-api contact.

## Technical notes
MuleSoft servers:

`dev.vapi.va.gov` - dev
`test.vapi.va.gov` - QA
`stage.vapi.va.gov` - stage
`vapi.va.gov` - prod

Format of yml (see [PR 8853](https://github.com/department-of-veterans-affairs/vets-api/pull/8853/files#diff-e769bbb8c1ba3711c5403b424ed9c218ffafba7f1890ee394717196f28ff4540R94)):

```
form_10_10cg:
  carma:
    mulesoft:
      mock: true
      host: "https://{{ val from above list}}"
      client_id: {{val from AWS parameter store}}
      client_secret: {{val from AWS parameter store}}
      timeout: 120
```

Contact Igor Khurgin (igor.khurgin@salesforce.com) for credentials.

---
## Tasks
- [ ] Ansible playbooks updated per environment
- [ ] ID/secrets stored per environment

## Acceptance Criteria 

10-10CG form data and attachments able to be submitted to CARMA Mulesoft.
