### ISSUE TITLE
Explore CI Integration of E2E Code Coverage Within GHA

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#37766]
# Description
Now that the Code Coverage report has been generated locally, go through the Cypress CI documentation - https://docs.cypress.io/guides/continuous-integration/introduction - and explore implementing an E2E Code Coverage generation within Github Actions that triggers on deploys and does not modify production code for instrumentation details.

## Tasks
- [x] Enable the successful run of Cypress Code Coverage within the CI/Github Actions workflow.
- [x] Upload of a code coverage artifact.

## Acceptance Criteria
- [x] Cypress Code Coverage summary is generated within the CI/Github Actions workflow.
- [x] Successful upload of a code coverage artifact.

**Comment by rjohnson2011** [comment]
In progress of going through Cypress documentation to determine the best methodology for implementing E2E code coverage checks on Github Actions on a production level.

**Comment by rjohnson2011** [comment]
Working on editing the Github workflows file according to https://github.com/marketplace/actions/cypress-io#component-tests

Testing out new branch to see if E2E coverage is being triggered by Github Actions.

**Comment by rjohnson2011** [comment]
Adding the following to the Github Actions workflow file:
```
steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v2.9.7
        with:
          start: yarn run ci:instrument
          wait-on: http://localhost:3000
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
```

Updating with a link to a new branch coming shortly & then testing the CI pipeline modifications.
