### ISSUE TITLE
[Vets-API/EKS] Deployment Requests and Limits

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#39691]
## Description
Evaluate the need for requests and limits for the Vets-API deployment and implement them if necessary.

## Background/context 
- Vets-API is a monolith (and resource-hungry) and care needs to be taken to make sure it has the resources necessary to operate as expected within EKS

## Technical notes
- Goldilocks could be leveraged here
- https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
- Understanding Kubernetes QoS would be beneficial here as well, https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/

---
## Tasks
- [ ] Evaluate the need for requests and limits
- [ ] Implement requests if necessary
- [ ] Implement limits if necessary

## Acceptance Criteria 
- [ ] Vets-API is deployed with appropriate resources based on evaluation

**Comment by rmtolmach** [comment]
Looking into resource management for k8s. Placing my findings here.

**resources** - Refers to CPU and memory
**requests** - If you specify a memory and/or CPU unit, the kube-scheduler uses that info to decide which node to place the pod on, basically ensuring the node can handle the heft. 
**limits** - if you specify a memory and/or CPU unit, this is the max amount of resources the container can consume, ensuring it doesn't use up more resources than we want it to.

It seems like “requests” and “limits” usually go together. If you sent one and not the other, Kubernetes will automatically set the one you didn’t set to match the one you did set. 

It would look something like this:
```
  containers:
  - name: app
    image: images.my-company.example/app:v4
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```

**Comment by rmtolmach** [comment]
Our `vets-api` server instances are running on `c5n.large` or `c5n.xlarge` instances. (`c5n` are for compute-heavy applications.) Here are the specs for these instances:
Instance Name | vCPUs | RAM | EBS Bandwidth | Network Bandwidth
-- | -- | -- | -- | --
c5n.large | 2 | 5.25 GiB | Up to 3.5 Gbps | Up to 25 Gbps
c5n.xlarge | 4 | 10.5 GiB | Up to 3.5 Gbps | Up to 25 Gbps

[source](https://aws.amazon.com/blogs/aws/new-c5n-instances-with-100-gbps-networking/)

Oseas helped me check Goldilocks for vets-api and here is that data:
![image](https://user-images.githubusercontent.com/10993987/164083955-7aef4de9-769d-4369-be3b-dee93adc96e1.png)
The "Current" numbers align with the numbers set in this file: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-tools-backend/vets-api/dev/deployment.yaml, so that makes sense. Here they are:
```
          name: vets-api-web
          ...
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
           ...
        - name: socat-proxy
          ...
          resources:
            requests:
              cpu: "100m"
              memory: "32Mi"
```
Key:
CPU units: m == millicpu == millicores. But you can also use no unit (where 1 == 1 CPU).
memory units: Mi == MiB == mebibyte == 1024^2 bytes

Conversions:
1 == 1 core == 1000m
0.1 == 0.1 core == 100m
53 MB = ~50 MiB
717 MB = ~683 MiB

The recommended CPU and memory requests/limits are far below what our `c5n` instances allow. Is this a concern?

Summary: Our `dev` instance is already using `requests`. According to Goldilocks, some of those numbers could be modified.
