### ISSUE TITLE
Prevent cross app imports from reappearing

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#41208]
## Description
Cross app imports have been making their way in the `vets-website` repo. Apps on the [allow list](https://github.com/department-of-veterans-affairs/vets-website/blob/master/config/changed-apps-build.json) are able to import from other apps without any issues if the app they are importing from isn't also being updated in the same branch. We want to prevent cross app imports from reappearing for apps on and off the allowlist.

Some possible options to preventing cross app imports from reappearing: 
- Create a custom ESLint rule to make developers aware they shouldn't be importing from other apps
- Add a job in CI that runs the [cross app import checker](https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/check-cross-app-imports.js) on changed apps that are on the allowlist, and blocks CI if new imports are added for the allowed app

## Definition of done
- [x] Determine whether a custom ESLint rule would be helpful in preventing cross app imports. If so, create one
- [x] Add a job in CI for checking cross app imports

**Comment by it-harrison** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/21093) for custom ESLint rule

**Comment by theodur** [comment]
A while ago, I briefly did some discovery work on adding a job in CI for preventing apps on the allowlist from adding new cross app imports. We have the [check-cross-app-imports](https://github.com/department-of-veterans-affairs/vets-website/blob/main/script/check-cross-app-imports.js) script that can help with this. The script has an option `--app-folder` that allows you to specify the root folder name of the app that you want to examine cross app imports for. It will log the output of the imports to the console in JSON format. If no cross app imports are found, the script will output the text: 
```
No cross app imports were found!
```
We can add a job to the [pull-request](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/pull-request.yml) workflow that uses this script for determining when a PR with changes to an app on the allowlist is creating cross app imports. Something like this could be a good start for the job:
``` yaml
jobs:
  check-cross-app-imports:
    name: Check Cross App Imports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/workflows/install
        timeout-minutes: 30
        with:
          key: ${{ hashFiles('yarn.lock') }}
          yarn_cache_folder: .cache/yarn
          path: |
            .cache/yarn
            node_modules
      
      - name: Get changed applications
        id: get-changed-apps
        uses: ./.github/workflows/get-changed-apps
        with:
          output-type: 'folder'

      - name: Generate cross app import report
        run: yarn check-app-imports --app-folder ${{ steps.get-changed-apps.outputs.folders }}
```
There will need to be logic added to the job that handles when to fail workflow runs, so that CI is blocked for PRs introducing cross app imports to already isolated apps.

The script only supports one app folder being passed into the `--app-folder` option, so it will probably need to be updated to handle multiple app folders, since a PR can contain changes to multiple apps on the allowlist. This should mostly involve a few things:
#### Updating the `appFolder` variable to store multiple folders passed from the `--app-folder` option. 

e.g. changing:

``` javascript
const appFolder = options['app-folder'];
```
to:
``` javascript
const appFolder = options['app-folder'].split(',');
```
#### Updating the `appPath` variable to prepend the `src/applications` to the app folder name. 

e.g. changing:

``` javascript
const appPath = path.join(__dirname, '../src/applications', appFolder);
```
to:
``` javascript
const appPaths = appFolder.map(folder =>
  path.join(__dirname, '../src/applications', folder),
);
```

#### Updating the `getCrossAppImports` function to handle returning cross app imports for multiple apps

The `getCrossAppImports` function is responsible for returning an object with the cross app imports per app. If `appFolder` is empty, it will return the entire cross app import graph for the repo, otherwise, it will return the cross app imports for only the `appFolder` that is passed into it. This function will probably need to be updated to filter the object to return cross app imports of the multiple apps that are specified.


**Note**: These are just some of the findings I came across when doing discovery work. Feel free to update/refactor anything as necessary for this ticket
