### ISSUE TITLE
[EKS] Verify configs between BRD and EKS vets-api

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#41253]
## Description
Double check that all of the needed configurations and files are put in place for the dev vets-api deployment

in order to do so I will be comparing dev 

BRD (mainly in deployment) - https://github.com/department-of-veterans-affairs/devops/tree/master/ansible
EKS - https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vsp-tools-backend/vets-api

to make sure that everything is synced properly so we aren't diving down rabbit holes if anything doesn't work.

## Background/context 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/35039

---
## Tasks
- [ ] create a checklist to make sure all files and configurations match between BRD and EKS dev
- [ ] verify that all of the appropriate secrets are also matching between credstash and parameter store

## Acceptance Criteria 
- [ ] all of the files and configurations that exist in BRD are up to date and exist in EKS dev

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by patrickvinograd** [comment]
Re the issue with fwdproxy connection getting an SSL error: 
vets-api BRD instances get the forward proxy's `self.crt` added to their trust store in 
ansible/build/roles/vets-api/tasks/main.yml
```
- name: Copy self signed forward proxy ELB cert (wildcard) to anchors
  copy:
    src: ../deployment/config/fwdproxy/self.crt
    dest: /etc/pki/ca-trust/source/anchors/forward-proxy.crt
    owner: root
    group: root
    mode: 0600
```
and then subsequently `update-ca-trust` and `update-ca-trust-enable` are executed.

I don't know what the equivalent would be for EKS.
