### ISSUE TITLE
Update URLs to include API vers 

### ISSUE THREAD

**Issue by ianhundere** [department-of-veterans-affairs/va.gov-team#41826]
# Description
As per:
https://github.com/department-of-veterans-affairs/devops/pull/11309
# Acceptance Criteria
- [x] Add `v0` to the necessary URLs in `apps/vsp-tools-backend/vets-api/dev/settings-configmap.yaml`:
```
    idme:
      redirect_uri: https://dev-api.va.gov/v0/sign_in/idme/callback
      dslogon_redirect_uri: https://dev-api.va.gov/v0/sign_in/dslogon/callback
      mhv_redirect_uri: https://dev-api.va.gov/v0/sign_in/mhv/callback
    logingov:
      redirect_uri: https://dev-api.va.gov/v0/sign_in/logingov/callback
```
