### ISSUE TITLE
Monitor Sidekiq with Datadog

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#49511]
## Description
[Datadog's native Sidekiq integration](https://docs.datadoghq.com/integrations/sidekiq/) is not set up.

It would be nice to be able to monitor the average/total run time of jobs in Sidekiq (by Job class).

Let's do that.

## Task
- [x] Enable Logging/Methods/Metrics/Functions documented in DD

## Acceptance Criteria

- [x] Logging/Methods/Metrics/Functions are able to called as documented

**Comment by oseasmoran73** [comment]
Created skeleton PR for vets-api to apply setting to Sidekiq. Punting that portion over to @ericboehs

**Comment by holdenhinkle** [comment]
Oseas' PRs:

- https://github.com/department-of-veterans-affairs/vets-api/pull/11543/files
- https://github.com/department-of-veterans-affairs/vets-api/pull/11511

**Comment by holdenhinkle** [comment]
Doing a bit of googling about how to add the `DD_DOGSTATSD_MAPPER_PROFILES` environment variable to the Datadog Agent. I found this - https://stackoverflow.com/questions/71246154/how-to-configure-dd-dogstatsd-mapper-profiles-in-datadog-airflow-integration

The var should be JSON.

I converted the YAML to JSON:
```
{
  "dogstatsd_mapper_profiles": [
    {
      "name": "sidekiq",
      "prefix": "sidekiq.",
      "mappings": [
        {
          "match": "sidekiq\\.sidekiq\\.(.*)",
          "match_type": "regex",
          "name": "sidekiq.$1"
        },
        {
          "match": "sidekiq\\.jobs\\.(.*)\\.perform",
          "name": "sidekiq.jobs.perform",
          "match_type": "regex",
          "tags": {
            "worker": "$1"
          }
        },
        {
          "match": "sidekiq\\.jobs\\.(.*)\\.(count|success|failure)",
          "name": "sidekiq.jobs.worker.$2",
          "match_type": "regex",
          "tags": {
            "worker": "$1"
          }
        }
      ]
    }
  ]
}
```

Regarding this string in the vsp-infra-k8s-datadog-agent repo - 

```
    steps:
      - uses: actions/checkout@v2
      - name: Set datadog integrations as environment variable
        run:
          cat versions.json | jq -r --arg prefix "integrations=" '$prefix + (.integrations|tostring)' >> $GITHUB_ENV
```

`.integrations` isn't being set anywhere in the repo. I'm assuming the integrations list is being generated from the `config/initializers/sidekiq.rb` file in vets-api...
