### ISSUE TITLE
Saturated vets-api server pod solution

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#49794]
## Description
When vets-api-servers are backlogged, are they taken out of rotation or still taking requests? Can they be flagged as "NotReady" to stop them from being further backlogged?

Additionally, are the current puma backlog metrics **only** accounting for those that are still serving traffic -- excluding the backlog count of those no longer taking traffic?

-----

**The current setup allows requests to hit pods that already have a backlog, and this solves that.
what the readiness-probe CM does:**
- runs [locally] in each pod
- hits the /stats endpoint and sums up the backlog
- the script exits using the backlog count (anything > 0 is considered an error)
- a failed readiness probe = keep the pod alive so that it can process the work it has, but don't send any more traffic to it
- the probe is executed every 5 seconds
- if the probe remains failed (backlog > 0) for 15 minutes the pod is terminated -- at this duration, i figure something has gone terribly wrong
- if readiness is already in a failed state but then succeeds (backlog = 0) two times in a row, it's marked as ready and begins receiving traffic
- i figure that a backlog of 0 should succeed twice before considering the pod ready (to make sure the pod has time to settle)

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  creationTimestamp: null
  name: readiness-probe
data:
  readiness.sh: |
    #!/bin/bash

    # Uses sum of backlog as the exit code
    #
    # If backlog is > 0 then the exit code indicates a failure and the readiness
    #   probe will fail. Once the backlog is back down to 0, the script will
    #   exit with a success and the pod will be placed back into rotation to
    #   accept traffic.

    exit $(
      curl -s 127.0.0.1:9293/stats \
      | grep -oE 'backlog":[0-9]*' \
      | cut -d':' -f2 \
      | awk -v SUM="0" '{ SUM += $1} END { print SUM }'
    )
```

**Adding to the deployment (image):**
1. Add the readiness-probe configmap as a volume to the deployment
2. this will be for the vets-api-web container
3. update the readiness probe settings for the vets-api-web container
mount the script to the container

![image (9).png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/6c6d361d-32a2-4410-8368-762281e6087d)

## Tasks
- [ ] Investigate how saturated pods receive/don't receive requests
- [ ] Investigate metrics
