### ISSUE TITLE
Failing K8s tests

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#58410]
## Description

In the K8s branch, during the automatic merge from master, there's some tests that fail (looks like something related to an undefined constant).

The same tests also fail in branches that are branched off of `k8s` - https://github.com/department-of-veterans-affairs/vets-api/pull/12639

Example:

```
Failures:

  1) EducationForm::Forms::VA1990e 1990e simple spool test generates the spool file correctly
     Failure/Error: windows_linebreak = EducationForm::WINDOWS_NOTEPAD_LINEBREAK

     NameError:
       uninitialized constant EducationForm::WINDOWS_NOTEPAD_LINEBREAK
```

```
Failed examples:

rspec './spec/jobs/education_form/forms/va1990e_spec.rb[1:2:1]' # EducationForm::Forms::VA1990e 1990e simple spool test generates the spool file correctly
rspec './spec/jobs/education_form/forms/va1990e_spec.rb[1:1:1]' # EducationForm::Forms::VA1990e 1990e kitchen_sink spool test generates the spool file correctly
rspec './spec/jobs/education_form/forms/va1995_spec.rb[1:2:1]' # EducationForm::Forms::VA1995 1995 kitchen_sink spool test generates the spool file correctly
rspec ./spec/jobs/education_form/forms/va1995_spec.rb:20 # EducationForm::Forms::VA1995#direct_deposit_type converts internal keys to text
rspec './spec/jobs/education_form/forms/va1995_spec.rb[1:1:1]' # EducationForm::Forms::VA1995 1995 minimal spool test generates the spool file correctly
rspec './modules/appeals_api/spec/services/appeals_api/pdf_construction/generator_spec.rb[1:1:3:2:4:1]' # AppealsApi::PdfConstruction::Generator#generate Higher Level Review v3 with max length generates the expected pdf
```

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/9326247/039fa3d0-6218-4358-8d83-9a7a7b58fa86)

**Comment by holdenhinkle** [comment]
I added the `platform-sev-s0 ` label because this issue is blocking code from being merged into `k8s` branch.

**Comment by holdenhinkle** [comment]
Trevor might have fixed these failing tests in this PR - https://github.com/department-of-veterans-affairs/vets-api/pull/12712#pullrequestreview-1431860325

**Comment by holdenhinkle** [comment]
Trevor's PR fixed a handful of the failures, but there are still other undefined constant failures.

The failures seem flakey. Some commits don't have any failures, some have the same 2 or 3 failures. Some just 1. Etc., etc..

commit/run - https://github.com/department-of-veterans-affairs/vets-api/actions/runs/5016049494/jobs/8992415772
```
Failures:

  1) BankName.get_bank_name with cached bank name returns the cached name
     Failure/Error: return if routing_number.blank? || routing_number == BGS::Service::EMPTY_ROUTING_NUMBER

     NameError:
       uninitialized constant BGS::Service
     # ./app/models/bank_name.rb:16:in `get_bank_name'
     # ./spec/models/bank_name_spec.rb:21:in `block (4 levels) in <top (required)>'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

  2) BankName.get_bank_name with cache miss returns the bank name and saves it in cache
     Failure/Error: return if routing_number.blank? || routing_number == BGS::Service::EMPTY_ROUTING_NUMBER

     NameError:
       uninitialized constant BGS::Service
     # ./app/models/bank_name.rb:16:in `get_bank_name'
     # ./spec/models/bank_name_spec.rb:29:in `get_bank_name'
     # ./spec/models/bank_name_spec.rb:34:in `block (5 levels) in <top (required)>'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/vcr-6.1.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/vcr-6.1.0/lib/vcr.rb:194:in `use_cassette'
     # ./spec/models/bank_name_spec.rb:33:in `block (4 levels) in <top (required)>'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

Finished in 2 minutes 25.7 seconds (files took 14.24 seconds to load)
2258 examples, 2 failures, 4 pending

Failed examples:

rspec ./spec/models/bank_name_spec.rb:20 # BankName.get_bank_name with cached bank name returns the cached name
rspec ./spec/models/bank_name_spec.rb:32 # BankName.get_bank_name with cache miss returns the bank name and saves it in cache
```

***

commit/run - https://github.com/department-of-veterans-affairs/vets-api/actions/runs/5015784255/jobs/8991805573
```
Failures:

  1) AppealsApi::PdfConstruction::Generator#generate Higher Level Review v3 with max length generates the expected pdf
     Failure/Error: expect(generated_pdf).to match_pdf(expected_pdf)
```

branch//run - https://github.com/department-of-veterans-affairs/vets-api/actions/runs/5015706301/jobs/8991619402
```
Failures:

  1) BankName.get_bank_name with cached bank name returns the cached name
     Failure/Error: return if routing_number.blank? || routing_number == BGS::Service::EMPTY_ROUTING_NUMBER

     NameError:
       uninitialized constant BGS::Service
     # ./app/models/bank_name.rb:16:in `get_bank_name'
     # ./spec/models/bank_name_spec.rb:21:in `block (4 levels) in <top (required)>'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

  2) BankName.get_bank_name with cache miss returns the bank name and saves it in cache
     Failure/Error: return if routing_number.blank? || routing_number == BGS::Service::EMPTY_ROUTING_NUMBER

     NameError:
       uninitialized constant BGS::Service
     # ./app/models/bank_name.rb:16:in `get_bank_name'
     # ./spec/models/bank_name_spec.rb:29:in `get_bank_name'
     # ./spec/models/bank_name_spec.rb:34:in `block (5 levels) in <top (required)>'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/vcr-6.1.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/vcr-6.1.0/lib/vcr.rb:194:in `use_cassette'
     # ./spec/models/bank_name_spec.rb:33:in `block (4 levels) in <top (required)>'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /usr/local/bundle/cache/ruby/3.2.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

Finished in 2 minutes 16.7 seconds (files took 14.26 seconds to load)
2258 examples, 2 failures, 4 pending
```

And
```
Failures:

  1) AppealsApi::PdfConstruction::Generator#generate Higher Level Review v3 with max length generates the expected pdf
     Failure/Error: expect(generated_pdf).to match_pdf(expected_pdf)
```

***

commit/run - https://github.com/department-of-veterans-affairs/vets-api/actions/runs/5015223769/jobs/8990493144
```
Failures:

  1) AppealsApi::PdfConstruction::Generator#generate Higher Level Review v3 with max length generates the expected pdf
     Failure/Error: expect(generated_pdf).to match_pdf(expected_pdf)
```
