### ISSUE TITLE
Update ArgoCD Terminal Access Request Template (and supporting docs)

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#59700]
The current template, while generally effective, is a bit confusing for requesters (specifically the various checkboxes that are meant to be a reference to support, not a TODO list), and generally leaves people in limbo for a LONG time (This [user](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58305) has been waiting for a month, despite providing everything we asked) because of the shifting requirements from OCTODE.

So, we should implement the following changes:
- [ ] Require a screenshot of EQIP (vs the checkbox, because Bill will ask for a screenshot anyway)
- [ ] Remove the confusing checkboxes (any support directions should go int support docs)
- [ ] Follow any other patterns from new [Sidekiq template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request%2Csidekiq-access-request&projects=&template=vetsapi-sidekiq-ui-access.yaml&title=Sidekiq+Admin+UI+access+for+%5Bindividual%5D) that might help here
- [ ] Update Internal Support Docs as necessary.

**Comment by ryan-mcneil** [comment]
Yeah, I understand. I think that if we get approval to remove some requirements, and I shape it similar to the Sidekiq request, I think I can satisfy your concerns. Will run it by ya.

**Comment by ryan-mcneil** [comment]
@BillChapmanUSDS Today I chatted with @little-oddball and several members on the support team to hash out some confusion surrounding the ArgoCD terminal access template, eQIP requirements, and your involvement in the process.

Currently, from a high level:
* The user fills out the request with necessary info, and adds their proof of eQIP transmittal
* We provide access to lower environments
* If Prod access is requested, we tag it accordingly to get your approval

The requirement of eQIP has caused a lot of confusion, as the current template suggests they only need to check a box that they've submitted the survey, while your requirement seems to be more strict than that (i.e. they must include a screenshot). This led to me creating this ticket.

However, during our call today we made a realization that should hopefully simplify this. ArgoCD is behind SOCKS, so this SHOULD imply that they have submitted their eQIP Transmittal and have had it approved, no? Asking again here seems redundant.

**Our recommendation for the updated process would be the following:**
* The user fills out the request with necessary info (No eQIP needed)
* Assuming all information was provided, we grant access to lower environments
* If Prod access is requested, we tag it accordingly to get your approval. You would no longer need to confirm eQIP (per this redundancy), only give your "blessing". This will hopefully expedite things both for you, and the requester trying to do their job.

I'll also note that we discussed new ways of handling the re-request:

**Short Term**
* We come up with some sort of explicit verbiage that tells the user to set a reminder that they need to come back to this ticket within 1 week of expiration and tell us that they need another 3 months. 
  * Per the backend docs, a reapproval can be given by a couple of our lead engineers, so we'll facilitate that. 
* If they do not respond, a couple days before expiration we'll bump them, and let them know it's going to expire. 
* If they fail to do so, we'll remove access and force them to go through the process again.

**Long Term**
Clearly this "short term" solution is still tedious. We intend on coming up with a more elegant, automated solution, and will put our heads together at some point and think through what that might look like.

Let me know your thoughts! Thanks!

**Comment by BillChapmanUSDS** [comment]
**Short Answer:** I think this sounds fine in the short term.  But I'd like it to be noted explicitly in the ticket that SOCKS access has already been granted, preferably by a team lead, COR, etc... The documentation is what we need, it's not about vetting as much right now. These tickets are currently serving as much of the documentation necessary for our ATO and therefore need to be complete. When they are complete, I almost always stamp them and move on with the occasional gripe about best practices when too much access is being required.  




**Long Answer**
The solution I have been discussing for ongoing access to production systems is two fold. For VFS Teams  I think platform can happily rubber stamp any request that has the blessing of a federally employed PO and a statement along the lines of "I acknowledge that this individual  has the approproriate expertise has gone through the appropriate steps to gain access to these systems, including the necessary preliminary security assessment (E-Qip etc.."

For a support team that lives under platform I think we want a more organized solution. 

In the long term we need better roles organization and assignment, if you fill a certain role you get the access that role needs and it's ongoing while you serve the role. But we also need fewer folks with direct access to production resources. Because we have these two issues happening at once and they both are at odds with each other, this solution is not moving quickly. 

@little-oddball  and I have talked a lot about this and I don't now that there are actually any truly technical hurdles, it really is an administrative problem right now. 

Support is one of those areas where a lot of access is often necessary and I'd love to discuss a solution piloted with support engineers that works as follows. 

Support team and leadership together decides the roles that are on the team and which access is appropriate for that, we discuss and refine them.  In the future it's just part of the onboarding workflow to a certain role.  Now we don't need to haggle over whether an individual needs that access, if they are being placed in a role we assume the appropriate vetting for that role has taken place.  The ticket to file for access is as simple as this person is in this role and they get this access while they are in this role.  Since all the vetting has taken place, we just need to find a more efficient way to verify E-Qip or something similar. 

 We shouldn't be granting granular, one-off access to our environments and any replacing process needs to acknowledge that.  I don't like the toil that the temporary access creates and the purpose of is more to keep the progress moving forward on a better process. I want a path to ongoing access for anyone serving a role that needs it and this will nee da combination of being way less permissions of who gets access, and a rational outline for what roles are being filed and what access they need.

**Comment by ryan-mcneil** [comment]
@BillChapmanUSDS This all makes sense and I completely agree with your long term goal. Role based permissions are the way to go, and every "good" modern platform utilizes them in some shape or another.

I do, however, want to circle back to SOCKS (with the understanding that documentation is what you're striving for). If having SOCKS is NEEDED (meaning they cannot physically access ArgoCD without it), is it necessary for it to be a requirement? It seems redundant. My goal here is to remove a step so that users don't spend weeks waiting to get access. 

Would adding a checkbox towards the top of the form containing something along the lines of the following suffice?:
`[ ] I certify that have SOCKS and understand I cannot access ArgoCD without it`
(I would also include a note telling them that if they don't have SOCKS to cancel this request, and link them to the SOCKS procedure/request form)

Worst case scenario, they mistakenly/malevolently check this box, get added to the respective Github teams (for lower Envs only, as they'd still need your approval for prod) and they still CANNOT access the ArgoCD UI because they don't have SOCKS.

If we instead require a `lead, COR, etc...` to confirm they have SOCKS, it's really not much more efficient (perhaps less convenient) than having them add a screen shot of an email that they may or may not have. We currently have contractors that have been on various projects with the VA for years, have SOCKS/PIV but don't have this email/know their date (which is understandable).

If your answer is unwavering, in that they either need eQIP or someone to explicitly confirm their SOCKS access, does their TRANSMITTAL DATE (vs screenshot) suffice? I understand that they can reach out to Amber/their VOR and get this. I would ultimately just replace the current checkbox at the top of the form with a text input for this date. This, I'll add leaves room for adding an arbitrary date, as the Support rep has no way of verifying in an efficient manner. 

Not to beat a dead horse, I just ultimately want as little back and forth as possible so we can get these people moving.

Thanks for your input!

**Comment by BillChapmanUSDS** [comment]
@ryan-mcneil  I'm never unwavering,  and thank you for your concern for making the process easier.  The worry I had with the individual certifying is there is nothing in the ticket that serves as a documented check and balance against it.   Part of the problem is that on the platform side we were spending a lot of time going back and forth with CORS and other leadership to verify, and while that work is not seen by the requestor, it greatly delays the time it takes to make a determination and ensure the documentation is in order.  I'm ok with a checkbox but the federal validation still needs to take place. I was suggesting we just understand it has to happen and have it done up front instead of having it done in the background. 

But you've sold me on this point: 

"Worst case scenario, they mistakenly/malevolently check this box, get added to the respective Github teams (for lower Envs only, as they'd still need your approval for prod) and they still CANNOT access the ArgoCD UI because they don't have SOCKS." 

I think the checkbox is acceptable in this case. 

[ ] I certify that have SOCKS and understand I cannot access ArgoCD without it. 

That's a good short term solution.

**Comment by rmtolmach** [comment]
You could have them add a link to their SOCKS (or AWS) request. Not to confuse things more, but I think we've only been requiring E-QIP for SOCKS since March 24 (in [this commit](https://github.com/department-of-veterans-affairs/va.gov-team/commit/14c09690f6c2a23833e10bb41df73a77d5574bd9)).

**Comment by ryan-mcneil** [comment]
@BillChapmanUSDS well Rebecca has shaken my confidence in my approach. What are you thoughts?

I can ask for them to provide 1 of these many things to prove their eQIP Transmittal, which adds back some complexity/potentially confusing verbiage. I also feel like there's a chance that users (like the ones that drove me to spin up this ticket) won't be able to check any of these boxes but still be qualified, as they've been around these programs for years, have clearance, but don't have these emails/issues.

Should we be worried that there might be users that have been around since before March 24 that might have SOCKS but have somehow flown under the radar and don't have clearance? They still would have had to be on the VFS Roster and have provided all of the other details.

**Comment by BillChapmanUSDS** [comment]
Yes, The list of folks without E-Qip documented was another concern I had. My hope was that since we are still doing 3 month  access limits,  The fix for that needs to be rolled in to the bigger long term solution that grants ongoing access. 

Thinking out loud: @rmtolmach  would it be possible for us to start a separate initiative, let's get EQuip documented for everyone that existed prior to the current process date. I can help with this but I'd like your thoughts.  For those folks many of them have actually been adjudicated already and the EQip submission is not really relevant anymore, we just use that for expedience.

I wonder if we should start collecting proof of adjudication,  then we only need EQip dates for new folks. 

But either way, if we come up with a sperate process for accounting for the "legacy" access folks we can simplify this process and the other is a one-off.

**Comment by rmtolmach** [comment]
Just for our understanding, why has EQIP proof become the gold standard for access approval? Is it because it's an ATO requirement?

**Clarifications:**

> let's get EQuip documented for everyone that existed prior to the current process date

Who is "everyone"? Everyone who has SOCKS access? 

>  For those folks many of them have actually been adjudicated already and the EQip submission is not really relevant anymore

By "adjudicated" you mean that they not only have submitted their EQIP, but it's been processed (and "approved" as well)? Is there any way to determine this? Can we assume you have the ability to confirm if someone has been adjudicated?

**Proposed way forward:**

If you need a list of users who have SOCKS access, we can provide that for you. We can identify the users who have gotten access since March 24 (proof of EQIP in the request form). If you can confirm the status of the "legacy" (pre-March 24) SOCKS users and comment on their SOCKS access request, then that would basically put everyone who has socks access on an allow-list of sorts. This would give us a paper trail, which is a requirement (correct me if I'm wrong on that). After this is done, everyone requesting ArgoCD terminal access _going forward_ would not need to share their EQIP screenshot because they've already passed through the SOCKS gate. We'd be using SOCKS access request as an implicit ticket to get Argo terminal access. How does this sound?

**Comment by ryan-mcneil** [comment]
Update: Last week I provided Bill with the following lists of SOCKS users, containing users that HAVE proof of eQIP attached to their GH SOCKS request, and users that do not. The latter will need to be confirmed by someone. I believe Bill will be working on this, but I have let him know I'm ready to help if needed. This morning Bill mentioned that he received a request for an audit of prod access yesterday, that may help move this along.

```
Modified lists from DEVOPS/ansible/global/config.yml
List of users with screenshots of WITH eQIP status (transimttal or adjudication) attached to SOCKS request:
  automation:
  - ian@docme360.com 
  automation_external:
  developers:
  - adrian.delacruz@agile6.com
  - alex.person@thoughtworks.com
  - aurora.hampton@agile6.com
  - bradley.bergeron@va.gov
  - brown_robert3@bah.com
  - christopher.floess@adhocteam.us
  - dakota.larson@oddball.io
  - daniel.dasilva@bylight.com
  - evan.smith@oddball.io
  - evan.ubiera@thoughtworks.com
  - hodges.glenn@va.gov
  - ian.perera@va.gov
  - jacob.uhteg@oddball.io
  - jennica.stiehl@oddball.io
  - joshua.drumm@agile6.com
  - kcoulter@pluribusdigital.com
  - kenneth.gary@va.gov
  - kevin.suarez@agil6.com
  - kyle.drewno@adhocteam.us
  - markchae@navapbc.com
  - matt.kelly@adhocteam.us
  - max.antonucci@agile6.com
  - micah.frazier@oddball.io
  - mmiller@pluribusdigital.com
  - nathan.burgess@corforma.io
  - nathan.wright@oddball.io
  - richard.davis@agile6.com
  - rmays@kindsys.us
  - rockwell.rice@oddball.io
  - sam.stuckey@oddball.io
  - samreen.zarroug@va.gov
  - sean.midgley@oddball.io
  - seth.darr@agile6.com
  - swapna.k@thoughtworks.com
  - thomas.blackwell@coforma.io
  - Thomas.Reynolds4@va.gov
  - tyler.fink@oddball.io
  - zac.yellowhorse@oddball.io
  drupal_developers:
  - christia.troyer@civicactions.com
  platform:
  - ben.allen@oddball.io
  - brandon.dech@oddball.io
  - gia.antoniades@adhocteam.us
  - jeremy.weiland@adhocteam.us
  - ryan.mcneil@oddball.io
  - samantha.jennings@oddball.io
  viewers:
  - david.kennedy@adhocteam.us
  - mashaeva_natalia@bah.com
List of users without eQIP attached to SOCKS request:
  automation:
  - simi.adebowale@adhocteam.us
  automation_external:
  - cms-admin@va.gov
  developers:
  - aaron.hietpas@libertyits.com
  - aaron.ponce@agile6.com
  - aaron.young@thoughtworks.com
  - adam.foster@libertyits.com
  - adam.stilton@libertyits.com
  - adamsonntag@C02R52QFG8WM.local
  - adewitt@thoughtworks.com
  - adrian.rollett@va.gov
  - afia.caruso@oddball.io
  - agarcia@clarityinnovates.com
  - ahmed.magdub@va.gov
  - ahsan.khan4@va.gov
  - alastair@adhocteam.us
  - alex.valencia@adhocteam.us
  - alex.wilson@oddball.io
  - alex@adhocteam.us
  - anam.masroor@va.gov
  - andrea.singh@adhocteam.us
  - andrew.bunker@adhocteam.us
  - andrew.gunsch@adhocteam.us
  - andrew.herzberg@adhocteam.us
  - andrew.rodiek@govcio.com
  - anish.kshatriya@adhocteam.us
  - anthony.kopczyk@oddball.io
  - antony.zimzores@libertyits.com
  - areyes@fearless.tech
  - aubrey@thesocompany.com
  - aurelio.nogueira@thoughtworks.com
  - austin.covrig@oddball.io
  - barry.egbert@va.gov
  - beau.grantham@libertyits.com
  - bell_james2@bah.com
  - benjamin.grider@libertyits.com
  - bill.wanamaker@oddball.io
  - braden.shipley@oddball.io
  - bradley.gross@va.gov
  - brandon.marrone@thoughtworks.com
  - brandyn.sullins@govcio.com
  - bratti_christopher@bah.com
  - brian.deconinck@adhocteam.us
  - brian.seek@civicactions.com
  - brittany.clausen@va.gov
  - bryan.schofield@libertyits.com
  - bryan@kindsys.us
  - burnett_matthew@bah.com
  - calvin.gonzalez@oddball.io
  - casey.williams@adhocteam.us
  - chandana.eluru@accenturefederal.com
  - charley.stran@oddball.io
  - chika.adibemma@adhocteam.us
  - chris.alexander@adhocteam.us
  - christina.gednalske@adhocteam.us
  - christine.kies@adhocteam.us
  - christine@cityfriends.tech
  - christopher.bratti@libertyits.com
  - corey.ferris@adhocteam.us
  - cwheeler@governmentcio.com
  - cwilmsen@fearless.tech
  - dan.hinze@adhocteam.us
  - daniel.cloud@adhocteam.us
  - dany.han@libertyits.com
  - david.lennon@libertyits.com
  - dbrown-va
  - dean.zaslow@adhocteam.us
  - derrick.ellerbie@agile6.com
  - devon.hills@adhocteam.us
  - Dimitar.Tzvetanov@va.gov
  - dina.steeve@adhocteam.us
  - drew.fisher@adhocteam.us
  - eddie.otero@oddball.io
  - eddieglenn@navapbc.com
  - elder_joseph@bah.com
  - eli.mellen@adhocteam.us
  - elizabeth.neal@agile6.com
  - emily.wilson@adhocteam.us
  - erik.lopez@ablevets.com
  - eugene.lynch@coforma.io
  - evan.parish@oddball.io
  - fernando.boza@accenturefederal.com
  - ffafara@thoughtworks.com
  - foster_adam@bah.com
  - garrett.rabian@coforma.io
  - gary.fong@va.gov
  - ggupta@kindsys.us
  - giang.nguyen@libertyits.com
  - giles.wells@oddball.io
  - gperlangeli@clarityinnovates.com
  - grodriguez@governmentcio.com
  - gstevenson@governmentcio.com
  - harshil.moradia@adhocteam.us
  - helene.mccarron@thoughtworks.com
  - hocine.halli@accenturefederal.com
  - holden.hinkle@oddball.io
  - ian.harrison@adhocteam.us
  - ian.laflamme@libertyits.com
  - ian.mcgonigle@oddball.io
  - Ioan.Dobrescu@va.gov
  - jacob.finnern@accenturefederal.com
  - james.bell@libertyits.com
  - jami.gibbs@adhocteam.us
  - jared@coforma.io
  - jarred.simon@va.gov
  - jason.conigliari@adhocteam.us
  - jayson.perkins@adhocteam.us
  - jcunha@omb.eop.gov
  - jeana.clark@adhocteam.us
  - jeff.wallace@oddball.io
  - jeff@adhocteam.us
  - jeffery.strickland@va.gov
  - jerek.shoemaker@adhocteam.us
  - jeremy.wu@oddball.io
  - jesse.cohn@adhocteam.us
  - jessica.sexton@libertyits.com
  - jhonny.gonzalez@oddball.io
  - jmills@kindsys.us
  - joe.hall@thoughtworks.com
  - joe.niquette@oddball.io
  - john.bramley@oddball.io
  - john.woolschlager@civicactions.com
  - jonathan.d@thoughtworks.com
  - jonathan@adhocteam.us
  - josh.kim@adhocteam.us
  - joshua.farrar@pif.gov
  - joy.whitt@va.gov
  - julia@adhocteam.us
  - kayla.watanabe@adhocteam.us
  - keith.osayande@adhocteam.us
  - kelly.smith@civicactions.com
  - kelly_jasmyn@bah.com
  - kenneth.santiago@morgan6.com
  - kerry.powell@adhocteam.us
  - kevin.cranmer@libertyits.com
  - kevin.duensing@adhocteam.us
  - khansa.ayari.hammami@accenturefederal.com
  - kris.pethtel@adhocteam.us
  - kristen.brown@adhocteam.us
  - krkrishn@thoughtworks.com
  - krutarth.joshi@adhocteam.us
  - kshitiz.shrestha@adhocteam.us
  - ksuriyamoorthy@kindsys.us
  - kyle.macmillan@oddball.io
  - labiba.hanif@va.gov
  - larry.crochet@libertyits.com
  - lee.deboom@oddball.io
  - lee_ashton@bah.com
  - lihan@adhocteam.us
  - lindseyhattamer@Lindseys-MacBook-Pro.local
  - lucas.draney@oddball.io
  - luke.guerry@va.gov
  - luke@verdance.co
  - mariah.sager@thoughtworks.com
  - mark.dewey@va.gov
  - mark.greenburg@adhocteam.us
  - Mark.Komosa@va.gov
  - matt.ng@adhocteam.us
  - matthew.christianson@adhocteam.us
  - matthew.mccollum@libertyits.com
  - McCollum_Matthew@bah.com
  - mconway@clarityinnovates.com
  - micahkchiang@gmail.com
  - michael.chaffee@va.gov
  - michael.chelen@va.gov
  - michael.harlow@va.gov
  - michael.kimball@oddball.io
  - Michael.monty@va.gov
  - michael.moyer@va.gov
  - michael.talbot@va.gov
  - michaeldelligatti@c02v40qhhtdg.users.bah.com
  - michel.mcdonald@adhocteam.us
  - mike.haley@adhocteam.us
  - mike.lumetta@adhocteam.us
  - mizan_ali@bah.com
  - mohammed.shamsuddin@va.gov
  - monica.ramirez@libertyits.com
  - napoleon.kernessant@va.gov
  - narin@adhocteam.us
  - nate.peterson@adhocteam.us
  - nathaniel.hillard@va.gov
  - nick.gaydosh@adhocteam.us
  - nick.sprinkle@oddball.io
  - nicola@adhocteam.us
  - noah.stern@va.gov
  - norman.knolhoff@va.gov
  - oleksii.morgun@va.gov
  - paul.touchton@b3groupinc.com
  - peter.hill@oddball.io
  - peyton.lucas@oddball.io
  - pherbert@thoughtworks.com
  - raina.huerta@thoughtworks.com
  - ramos_andrew@bah.com
  - ray.messina@adhocteam.us
  - rccassity@gmailcom
  - rian.fowler@adhocteam.us
  - riley.anderson@oddball.io
  - ritesh.patel@adhocteam.us
  - rob@oddball.io
  - robert.hasselle@oddball.io
  - robert.perea-martinez@adhocteam.us
  - robin.bell1@va.gov
  - robin.garrison@adhocteam.us
  - rocio@coforma.io
  - roth_matthew@bah.com
  - ryan.johnson@oddball.io
  - ryan.koch@agile6.com
  - ryan.mcauliffe@ablevets.com
  - ryan.shaw@adhocteam.us
  - sal.gutierrez@adhocteam.us
  - sam.cormier@coforma.io
  - scott.james@gcio.com
  - scott.meyers@coforma.io
  - sdickson@greenthreadsllc.com
  - sebastian.caso@accenturefederal.com
  - shawkey_daniel@bah.com
  - shoaib.sheikh@va.gov
  - simi.adebowale@adhocteams.us
  - sriparna.sengupta@va.gov
  - stephen.barrs@va.gov
  - steve.albers@va.gov
  - steven.bair@libertyits.com
  - steven.brush@va.gov
  - steven.long@adhocteam.us
  - steven.templeman@oddball.io
  - suraj.basnet@accenturefederal.com
  - teagan.stephenson@bracari.com
  - theo@adhocteam.us
  - thomas.ferrin@adhocteam.us
  - tj@adhocteam.us
  - tmcmurdo@meetveracity.com
  - tom.harrison@adhocteam.us
  - tony.williams@va.gov
  - trevor.bosaw@oddball.io
  - tuong.ngo@bylight.com
  - tze@adhocteam.us
  - vhahacmcgibj@MacBook-Pro.fios-router.home
  - victoria.saleem@va.gov
  - vid.jovanovic@bylight.com
  - Weisz_John@bah.com
  - wesley.matheny@va.gov
  - will.huang@adhocteam.us
  - won.choi@va.gov
  - yangyang@navapbc.com
  - yoomlam@navapbc.com
  - zekiyaren@accenturefederal.com
  drupal_developers:
  - cms-ansible
  - edmund.dunn@agile6.com
  - eric.oliver@agile6.com
  - nathan.douglas@agile6.com
  - steve.wirt@civicactions.com
  - troy.griffin@agile6.com
  platform:
  - curt.bonade@oddball.io
  - cyril.atarah@oddball.io
  - dan.turner@adhocteam.us
  - eric.boehs@oddball.io
  - erica.sauve@adhocteam.us
  - hector.barreto@oddball.io
  - jeremy.britt@oddball.io
  - jesse.house@adhocteam.us
  - john.stevens-garmon@oddball.io
  - kyle.matheny@oddball.io
  - Lindsey.Hattamer@oddball.io
  - rebecca.tolmach@adhocteam.us
  - ryan.beckwith@oddball.io
  viewers:
  - abdiel.fernandez@oddball.io
  - adam.whitlock@adhocteam.us
  - alayna@adhocteam.us
  - alex.taker@adhocteam.us
  - allison.christman@oddball.io
  - allison@cityfriends.tech
  - andrew.ramos@libertyits.com
  - angela.agosto@adhocteam.us
  - angela.fowler@adhocteam.us
  - barry.melton@va.gov
  - ben.brasso@agile6.com
  - blake.organ@civicactions.com
  - bradley.gross@b3groupinc.com
  - branden.bartlett@accenturefederal.com
  - brian.gryth@adhocteam.us
  - cesar.santiago@accenturefederal.com
  - cevans@thesocompany.com
  - christian.burk@civicactions.com
  - christopher.johnston2@va.gov
  - clint.little@oddball.io
  - daniel.sasser@agile6.com
  - dave.pickett@civicactions.com
  - dawn@adhocteam.us
  - dorothy.biederman@va.gov
  - edison.velez@libertyits.com
  - emily@adhocteam.us
  - emily@oddball.io
  - eric.voshall@adhocteam.us
  - ero.gray@civicactions.com
  - evan.clendenning@libertyits.com
  - ewez.farhang@accenturefederal.com
  - fahmed@governmentcio.com
  - Frank.hiatt@adhocteam.us
  - gary.fallon@oddball.io
  - heather.justice@adhocteam.us
  - jacob.worrell@adhocteam.us
  - jason.woodman@oddball.io
  - jen.ecker@adhocteam.us
  - jennifer.strickland@adhocteam.us
  - jesse.abando@libertyits.com
  - jessica.stump@adhocteam.us
  - jill.adams@agile6.com
  - jill.taylor@oddball.io
  - joann@cityfriends.tech
  - john.borden@adhocteam.us
  - jonathan.nelson@adhocteam.us
  - jordan.wood@civicactions.com
  - joshua.hulbert@libertyits.com
  - justice_joseph@bah.com
  - kabrown@thoughtworks.com
  - kelly@adhocteam.us
  - kendra@adhocteam.us
  - kevin.gin@adhocteam.us
  - kyle.crockett@oddball.io
  - kyle.soskin@adhocteam.us
  - lainey.trahan@adhocteam.us
  - laura.flannery@civicactions.com
  - laurenconrad1993@gmail.com
  - leanna@adhocteam.us
  - lee.helmer@adhocteam.us
  - lenae.storey@adhocteam.us
  - leroy.michaelson@accenturefederal.com
  - liam.mccormick@accenturefederal.com
  - liz.lantz@adhocteam.us
  - lori.pusey@agile6.com
  - ltrombley@governmentcio.com
  - marc.heusser@adhocteam.us
  - martha.wilkes@va.gov
  - matt.long@adhocteam.us
  - mgayle@governmentcio.com
  - michael.hobson@adhocteam.us
  - michelle.middaugh@adhocteam.us
  - mmcguire@governmentcio.com
  - nathaniel.buck@accenturefederal.com
  - nguyen_giang@bah.com
  - nick.bloom@agile6.com
  - nick.osmanski@amida.com
  - Pat.Siebenlist@adhocteam.us
  - patrick.bateman@va.gov
  - peter.branam-lefkove@libertyits.com
  - peter.russo@adhocteam.us
  - pshort@governmentcio.com
  - ro.stokes@civicactions.com
  - robyn.singleton@adhocteam.us
  - ryan.link@oddball.io
  - ryan.smith@adhocteam.us
  - sade@coforma.io
  - santiago_kenneth@bah.com
  - sara.sterkenburg@adhocteam.us
  - shawna@adhocteam.us
  - ssimmorins@clarityinnovates.com
  - stefanie.gray@agile6.com
  - steven.kovacs@va.gov
  - taylor.mitchell@gcio.com
  - therese.dickson@adhocteam.us
  - tim.cosgrove@agile6.com
  - tony.valdez@accenturefederal.com
  - tony.whittaker@adhocteam.us
  - travis.cahill@agile6.com
  - tyler.snell@adhocteam.us
  - vicky.bellissimo@adhocteam.us
  - wesley.rowe@agile6.com
  - zach.park@agile6.com
```
