### ISSUE TITLE
[sign-in-service] - Fix 'Update manifest image tag' to account for new yaml format

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#59832]
## Issue Description
The new helm charts format changed with the addition of the child-charts. Everything gets moved under this charts name
```yaml
sign-in-service:
  appName: sign-in-service
  deploymentEnv: dev
  image:
    value: ~
    tag: ~
    pullPolicy: ~
```
Update the `Update manifest image tag` step in  `_deploy_environment.yml` workflow to account for this change.

## Backend tasks
- [ ] Update yml parsing

## Acceptance Criteria
- [ ] Image tag successfully update in vsp_application_manifest repo
