### ISSUE TITLE
Database Migrations - Occurs Automatically upon Deployment 

### ISSUE THREAD

**Issue by kingbmike** [department-of-veterans-affairs/va.gov-team#63141]

**Comment by kingbmike** [comment]
When we deploy we should have some line in deployments that run migrations during deployment OR come up with different scheme. 
-This would have to be after the container is up
-Make sure migrations are completed before container(s) are swapped over to new ones
-Investigate what a common migration pattern typically is

**Comment by bosawt** [comment]
Looking into this, if this is gonna be a Github action, it is likely it will need to be a 'self hosted' runner, as it needs to run the migration command within the same VPN the database is on

**Comment by bosawt** [comment]
There's documentation here, but I'm not sure if it's up to date: https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114812/On-Demand+Github+Self-Hosted+Runners

**Comment by bosawt** [comment]
Also this is apparently an example of the self-hosted runners in the frontend CI flow: https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/continuous-integration.yml

**Comment by bosawt** [comment]
using the documentation from the Atlassian article above, maybe it'd look something vaguely like this (as is I don't think this will work, but perhaps it resembles something that would work)?

```
name: Migrate Database

on:
  workflow_dispatch

env:
  INSTANCE_TYPE: c5.4xlarge
  MIGRATION_TAG: migration_tag
  POSTGRES_DB: blah
  POSTGRES_USER: blah
  POSTGRES_PASSWORD: blah
  POSTGRES_HOST: blah
  RAILS_ENV: development

jobs:
  start-runner:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1

      - name: Get bot token from Parameter Store 
        uses: marvinpinto/action-inject-ssm-secrets@latest 
        with: 
          ssm_parameter: /devops/VA_VSP_BOT_GITHUB_TOKEN
          env_variable_name: VA_VSP_BOT_GITHUB_TOKEN  

      - name: Get latest GHA Runner AMI ID
        run: |
          echo "RUNNER_AMI_ID=$(aws ec2 describe-images \
          --owners 008577686731 \
          --filters Name=name,Values=packer-gha-runner-ubuntu2004* \
          --filters Name=state,Values=available \
          --query 'sort_by(Images,&CreationDate)[-1].ImageId'
          --output text)" >> $GITHUB_ENV

      - name: Get Subnet with the most free IPs
        run: |
          echo "SUBNET_ID=$(aws ec2 describe-subnets \
          --filters "Name=tag:Name,Values=dsva-vagov-utility-subnet-2*" \
          --query 'sort_by(Subnets,&AvailableIpAddressCount)[-1].SubnetId'
          --output text)" >> $GITHUB_ENV

      - name: Start EC2 Runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ env.VA_VSP_BOT_GITHUB_TOKEN }}
          ec2-image-id: ${{ env.RUNNER_AMI_ID }}
          ec2-instance-type: ${{ env.INSTANCE_TYPE }}
          subnet-id: ${{ env.SUBNET_ID }}
          security-group-id: sg-0e23b56be3798e3a1
          aws-resource-tags: >
            [
              {"Key": "Name", "Value": "dsva-vagov-vets-website-on-demand-runner"},
              {"Key": "project", "Value": "vagov"},
              {"Key": "office", "Value": "dsva"},
              {"Key": "application", "Value": "on-demand-gha-runner"},
              {"Key": "VAECID", "Value": "AWG20180517003"},
              {"Key": "environment", "Value": "utility"}
            ]

  database-migration:
    name: Migrate Database for environment
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: ${{ env.MIGRATION_TAG }}
        provenance: false
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Setup environment
      run: env > env.list

    - name: Setup database
      run: |
        docker run --rm \
        --network ${{ job.services.postgres.network }} \
        --env-file env.list \
        ${{ env.MIGRATION_TAG }} /bin/sh -c 'bin/rails db migrate'

  stop-runner:
    name: Stop on-demand-runner
    needs: 
      - start-runner
      - database-migration
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1
          
      - name: Get bot token from Parameter Store 
        uses: marvinpinto/action-inject-ssm-secrets@latest
        with: 
          ssm_parameter: /devops/VA_VSP_BOT_GITHUB_TOKEN
          env_variable_name: VA_VSP_BOT_GITHUB_TOKEN

      - name: Stop Runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ env.VA_VSP_BOT_GITHUB_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
```
