### ISSUE TITLE
Prep VFS Teams Test Forms

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#64879]
### Problem Statement
VFS teams need a head start and plan to test the emis forms. Rebecca and Lainey to include info on this in the cutover plan.

### ACTIONS
- [ ] Communicate with relevant VFS teams (in table in the comments) to prep them for testing timeline

### DEFINITION OF DONE
- [ ] Relevant teams are aware of testing needed and timeline

**Comment by LindseySaari** [comment]
@rmtolmach Started on this in the cutover plan. Place details in this ticket.

**Comment by rmtolmach** [comment]
Copying https://github.com/department-of-veterans-affairs/va.gov-team/issues/61659#issuecomment-1734488426 here:

## Determine which teams (and forms) need to be tested re prefill
Ideally all of the teams listed in the table below.

### Research
I went through all of the files in [config/form_profile_mappings](https://github.com/department-of-veterans-affairs/vets-api/tree/master/config/form_profile_mappings) and pulled out the lines that were calling military_information. 

1010ez
```yaml
lastServiceBranch: [military_information, hca_last_service_branch]
lastEntryDate: [military_information, last_entry_date]
lastDischargeDate: [military_information, last_discharge_date]
discharge_type: [military_information, discharge_type]
postNov111998Combat: [military_information, post_nov111998_combat]
swAsiaCombat: [military_information, sw_asia_combat]
```

0873, FEEDBACK-TOOL
```yaml
  branchOfService: [military_information, last_service_branch]
  serviceDateRange:
    from: [military_information, last_entry_date]
    to: [military_information, last_discharge_date]
```

VIC
```yaml
verified: [military_information, vic_verified]
```

21-526ez
```yaml
servicePeriods: [military_information, service_periods]
reservesNationalGuardService:
  obligationTermOfServiceDateRange: [military_information, latest_guard_reserve_service_period]
```

26-1880. This would cover: 22-0994; 22-1990, 22-1990EZ, 22-1990N; 22-5490, 22-5495 which have a combination of these three attributes
```yaml
periodsOfService: [military_information, tours_of_duty]
currentlyActiveDuty: [military_information, currently_active_duty_hash]
activeDuty: [military_information, currently_active_duty]
```
### Ownership
Checked [Atlas](http://platform-codeowners.vfs.va.gov/product_directory/files?path_scope=config%2Fform_profile_mappings)
| Form     | GitHub Team                           | Contacted | Slack channel |
| -------------- | ------------------------------------ | ------------------ | ---- |
| `1010ez`       | [vfs-10-10](https://github.com/orgs/department-of-veterans-affairs/teams/vfs-10-10)                            | | # 1010-dev-team |
| `0873`         | [vfs-virtual-agent-chatbot](https://github.com/orgs/department-of-veterans-affairs/teams/vfs-virtual-agent-chatbot)            | | #va-virtual-agent-public |
| `FEEDBACK-TOOL`| [vfs-authenticated-experience](https://github.com/orgs/department-of-veterans-affairs/teams/vfs-authenticated-experience) or [my-education-benefits](https://github.com/orgs/department-of-veterans-affairs/teams/my-education-benefits) | | #authexp-engineering or #education-benefits (very quiet) |
| `VIC`          | None. Before Platform 😟                   | |
| `21-526ez`     | [Disability-Experience](https://github.com/orgs/department-of-veterans-affairs/teams/Disability-Experience)            | | #benefits-disability |
| `26-1880` | [vsa-ebenefits](https://github.com/orgs/department-of-veterans-affairs/teams/vsa-ebenefits) |  | Micah Chiang  |
