### ISSUE TITLE
not all values in va profile facilities are real

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#6807]
## What happened?
When making the `GET /v0/user` request on the vets-api, not all of the facilities values listed in the va profile attribute are actually facilities.  It appears that the regex gathering that data is also pulling out VHA identifiers like MVI id.

## Steps to Reproduce
- log into the va.gov website as judy.morrison@id.me
- GET /v0/user
- note that the last 2 facilities listed within the va profile attribute are NOT facitlities

![Screen Shot 2020-03-12 at 10 23 06 AM](https://user-images.githubusercontent.com/170002/76541624-1ec37800-6441-11ea-98e3-84606fa7f168.png)

**Comment by patrickvinograd** [comment]
Those 200xyz values are system identifiers, e.g. the user's MHV identifier is the MHS one. I think 200 is a "special" value in MVI - will get confirmation that  we  are safe to skip any values that are "200 + a suffix", i.e. not interpret them as a facility ID

**Comment by patrickvinograd** [comment]
Oh  and  also  I remembered that we added a configurable range  of values that we match  agains  to determine if somebody is a "VA  patient" or not for purposes of MHV  account eligibility. See this config stanza:
```
mhv:
  # include ranges first, then individual exceptions to the ranges last.
  facility_range: [[358,718],[720,740],[742,758]]
  facility_specific: [['741MM']] # 741 is excluded, but 741MM is included
```
