### ISSUE TITLE
Research Quality of Service for Kubernetes

### ISSUE THREAD

**Issue by vidjovanovic** [department-of-veterans-affairs/va.gov-team#68463]
Prod will have higher resources requirements than Dev and Staging for sign-in-service. We can up the memory and CPU limits for the resources within the values.yaml for each respective environment, but it would be prudent to research and add a Quality of Serivce class to our helm charts.

- [x] Read documentation here: https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/ 
- [x] Check node group instance types and sizes
- [x] Research if we need to change resource limits within values.yaml or if QoS is required

**Comment by vidjovanovic** [comment]
Quality of Service (QoS) classes in Kubernetes can ensure that our pods for Sign-in-service and Identity-dashboard applications receive the appropriate level of resource allocation and prioritization. All information for this research is taken from: https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/



1. Establish research requirements:
Identify high,moderate and low usage. 
We have relatively high usage in Prod, and for staging and dev it won’t be a big worry. We can specify resource limits in our values.yaml as well.

2. **Resource Requests and Limits:**


   Example snippet in our pod specification:

   ```yaml
   resources:
 	requests:
   	memory: "256Mi"
   	cpu: "100m"
 	limits:
   	memory: "512Mi"
   	cpu: "500m"
   ```

3. **Pod Priority and Preemption:**

From Kubernetes docs:
   “Kubernetes introduced the concept of pod priority and preemption to control scheduling preferences. Assign different priorities to your pods based on their importance. Pods with higher priority will be scheduled before lower priority pods. You can define priority classes using the `PriorityClass` resource.”

   Example priority class definition:

   ```yaml
   apiVersion: scheduling.k8s.io/v1
   kind: PriorityClass
   metadata:
 	name: high-priority
   value: 1000000
   ```


4. 
Criteria
For a Pod to be given a QoS class of Guaranteed:
Every Container in the Pod must have a memory limit and a memory request.
For every Container in the Pod, the memory limit must equal the memory request.
Every Container in the Pod must have a CPU limit and a CPU request.
For every Container in the Pod, the CPU limit must equal the CPU request.

   ```
