### ISSUE TITLE
Test form 26-1880 for VA Profile pre-fill

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#69260]
This form doesn't have a team anymore, so the Platform Product team will test it ourselves. From this comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/64879#issuecomment-1739929634 we need to test to make sure these fields get prefilled:
```yaml
periodsOfService: [military_information, tours_of_duty]
currentlyActiveDuty: [military_information, currently_active_duty_hash]
activeDuty: [military_information, currently_active_duty]
```
Link to the form in staging: https://staging.va.gov/find-forms/about-form-26-1880/

### Tasks
- [x] Log onto staging with a user that has service history
- [x] Start filling out the form and see if the service periods and active duty information are prefilled

### Validation
- [ ] Read comments and make sure everything looks good.
