### ISSUE TITLE
review MHV account upgrade errors 

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#7034]
Review the events in Sentry related to MHV account creation and upgrade.  

For example - 
http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/59514/events/430efb037947438298c7f299309e1f75/
suggest we are missing some error types. 
````
MHVACCTCREATION117:
  code: 'MHVACCTCREATION117'
  detail: 'A data integrity issue was encountered'
  status: <http status code you want rendered (400, 422, etc)>
  source: ~`
````
As a carry-over to this issue.
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16998
