### ISSUE TITLE
Configure Deny Windows for Code freezes

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#73380]
Deny windows explicitly deny synchronization during specific time windows. Currently, applying a code freeze is a manual process. Configuring Deny Windows for code freezes would eliminate this manual process and developers would not have to set up a code freeze for every event. Every year, the deny window schedules should be to modified to ensure the code freeze dates are correct. 

**Current Code Freeze Schedule**
- 1/15/2024 - Martin Luther King Jr. Day
- 5/27/2024 - Memorial Day
- 6/19/2024 - Juneteenth
- 7/4/2024 - Independence Day
- 9/2/2024 - Labor Day
- 11/11/2024 - Veteran's Day
- 11/28 - 11/29 - Thanksgiving
- 12/23 - 1/3/2025 - Holiday Freeze

**Testing**
- [x] Test Deny window in dev and staging
- [x] Ensure deny windows will work with the current sync window

Configuration:
```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  syncWindows:
  - kind: deny
    schedule: '0 * 15 JAN *' # MLK
    duration: 24h
    applications:
    - 'vets-api-prod'
    - 'vets-api-sandbox'
  - kind: deny
    schedule: '0 * 27 MAY *' # Memorial Day
    duration: 24h
    applications:
    - 'vets-api-prod'
    - 'vets-api-sandbox'
  - kind: deny
      schedule: '0 * 19 JUN *' # Juneteenth
      duration: 24h
      applications:
      - 'vets-api-prod'
      - 'vets-api-sandbox'
  - kind: deny
      schedule: '0 * 2 SEP *' # Labor Day
      duration: 24h
      applications:
      - 'vets-api-prod'
      - 'vets-api-sandbox'
  - kind: deny
        schedule: '0 * 28 NOV *' # Thanksgiving
        duration: 48h
        applications:
        - 'vets-api-prod'
        - 'vets-api-sandbox'
  - kind: deny
        schedule: '* * 23 DEC *' # Holiday Freeze
        duration: 12d # Not sure if day duration will work
        applications:
        - 'vets-api-prod'
        - 'vets-api-sandbox'
```
