### ISSUE TITLE
Discovery: Sync AWS Maintenance Windows with PagerDuty

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#77698]
## Description
Our tools regularly undergo maintenance. Maintenance windows within AWS include various operations, including software updates, security patches, and system upgrades  (planned and unplanned - example: a CVE patch). However, these maintenance activities are not currently reflected in PagerDuty, leading to potential alert fatigue and unnecessary escalations during planned downtimes. To streamline our incident management process and reduce noise for oncall folks, we need a solution to automatically sync AWS maintenance windows with PagerDuty maintenance windows.

## Tasks
- [x] Research integration options - How do we integrate this with Pagerduty

## Success Criteria
- [x] That there is a path forward with synching AWS Maintenance Windows with PagerDuty, _or_ that it is determined that it is not possible to do so. 

## Acceptability Criteria
- [ ] A maintenance window scheduled in AWS automatically creates a corresponding maintenance window in PagerDuty
- [ ] Updates or cancellations to AWS maintenance windows are reflected in PagerDuty
- [ ] Documentation is provided and up to date

**Comment by jennb33** [comment]
Need to talk with support about available maintenance windows. Moving this ticket to the next Sprint.

**Comment by jennb33** [comment]
Need to investigate how maintenance windows are set:
- AWS automates these
- Sometimes terraform

Terraform documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group.html#maintenance_window

**Comment by rjohnson2011** [comment]
Here are discovery findings for PagerDuty automation for each of the following:

## AWS Console
AWS can be integrated with PagerDuty via CloudWatch using the event rule "EC2 Instance System Maintenance" - https://support.pagerduty.com/docs/amazon-cloudwatch-integration-guide
1. Set up the PagerDuty Integration in AWS
Go to the AWS Management Console and navigate to the CloudWatch service.
In the CloudWatch console, go to "Configuration" > "AWS Service Delivery" > "Integration with AWS Services."
Click on "Pagerduty" and follow the instructions to set up the integration by providing your PagerDuty Service API Key.
2. Create a CloudWatch Event Rule:
In the CloudWatch console, go to "Events" > "Rules" and click on "Create rule."
Under "Event Source," choose "AWS services" and select "EC2" as the service name.
For "Event Type," select "EC2 Instance System Maintenance" event types.
3. Configure the Target:
Under "Targets," choose "PagerDuty" from the list of available target types.
4. Review and Create the Rule:
Review the rule details and click on "Create rule" to save the CloudWatch Event Rule.
5. Test the Integration:
You can test the integration by manually triggering a test event in the CloudWatch console.
Go to "Events" > "Rules" and select the rule you just created.
Click on "Test" and follow the instructions to create a test event.
Verify that you receive an alert in PagerDuty for the test event.

## Terraform
A maintenance window argument is passed in terraform. 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group.html#maintenance_window
One possible way to automate this would be through Github Actions:
1. Set up a GitHub Actions Workflow:
In your GitHub repository, create a new workflow file (e.g., .github/workflows/update-pagerduty-maintenance.yml).
This workflow will be triggered whenever your Terraform files are updated or when a new maintenance window is defined.
2. Define the Workflow Steps:
Below is example code for the following--
The workflow is triggered whenever files in the terraform/ directory are updated.
The Parse Terraform Files step should contain the logic to parse your Terraform files and extract the maintenance window settings. The parsed settings are then stored as an output.
The Update PagerDuty Maintenance Window step uses the official PagerDuty Action to update the maintenance window in PagerDuty based on the extracted settings.
```
name: Update PagerDuty Maintenance Window

on:
  push:
    paths:
      - 'terraform/**'  # Trigger the workflow when Terraform files are updated

jobs:

  update-maintenance-window:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Parse Terraform Files
      id: parse-terraform
      run: |
        # Parse Terraform files to extract maintenance window settings
        # Example: maintenance_window=$(parse_maintenance_window_from_tf_files)
        echo "::set-output name=maintenance_window::$maintenance_window"
        
    - name: Update PagerDuty Maintenance Window
      uses: PagerDuty/pagerduty-action@v1
      with:
        token: ${{ secrets.PAGERDUTY_TOKEN }}
        maintenance_window_id: ${{ secrets.PAGERDUTY_MAINTENANCE_WINDOW_ID }}
        start_time: ${{ steps.parse-terraform.outputs.maintenance_window.start_time }}
        end_time: ${{ steps.parse-terraform.outputs.maintenance_window.end_time }}
        description: ${{ steps.parse-terraform.outputs.maintenance_window.description }}
```
