### ISSUE TITLE
Develop a Strategy for Automated Tests of the PE Control Plane

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#78412]
# Description
Given the attributes of the control plane to act as a REST API that is agnostic to the system consuming it, we should devise a means for developing automated tests that does not rely on a specific front-end experience to feed into the API. Possibilities include --
* Contract tests -- some difficulty here in that we won't have a "consumer" side of the equation to start with
  * Pact
* API tests
  * Postman
  * JMeter
  * Rest Assure
  * etc.

## Tasks
1. Examine the possible test methodologies that we can use to test this new API
2. After choosing a test methodology, survey the possible tools and create a capability / evaluation matrix
3. Meet with stakeholders to make a decision
4. Record the decision in Confluence

## Acceptance Criteria
- [x] We have selected a test methodology for automatically verifying the capabilities of the control plane API
- [x] We have recorded the decision in a decision log document in Confluence
- [x] We have selected a tool for creating the automated tests

**Comment by pjhill** [comment]
I created a Postman collection based on the Swagger documents that Patrick created. [<img src="https://run.pstmn.io/button.svg" alt="Run In Postman" style="width: 128px; height: 32px;">](https://app.getpostman.com/run-collection/15306072-19666fef-7d3f-48d2-b61a-dca56fa2ea92?action=collection%2Ffork&source=rip_markdown&collection-url=entityId%3D15306072-19666fef-7d3f-48d2-b61a-dca56fa2ea92%26entityType%3Dcollection%26workspaceId%3Dfd818ef2-f77c-4122-8f45-1f84bb5eb7a3)

**Comment by pjhill** [comment]
Postman offers up the following snippet to get execution of the test collection going inside a GHA CI workflow --

```
name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "15306072-19666fef-7d3f-48d2-b61a-dca56fa2ea92" -e "15306072-aa90a95b-b4a3-477b-91ad-fc290f8fbcb1"
```
