### ISSUE TITLE
Create Benefit Intake Service deployed environment configuration

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#80871]
create the deployed environment configuration keys for the benefit intake service

https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-Secretvalues
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/

https://dsva.slack.com/archives/CDRSFMWFL/p1713283849965439

```
production:
    host: https://api.va.gov
    path: /services/vba_documents
    version: v1
    api_key: ~
    use_mocks: false

# dev and staging will use sandbox params
sandbox:
    host: https://sandbox-api.va.gov
    path: /services/vba_documents
    version: v1
    api_key: ~
    use_mocks: false
```
