### ISSUE TITLE
10-7959f-1 - Pre-fill not working for logged in users

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#81646]
**Issue**: For the logged in user viewing 10-7959f-1 on staging, the information from their profile is not pre-filled in the form fields.
**Current result**: the fields are blank and the user has to manually fill in
**Expected result:** 
- the fields would be pre-filled with their profile information when they are signed in 
- a logged in user should also be able to save their progress if they leave the form without completing.

**Comment by marywang2** [comment]
Related to this [back end ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/80367)

**Comment by balexandr** [comment]
@reiting Here is the mapping I created in the backend:
```
veteran:
  dateOfBirth: [identity_information, date_of_birth]
  fullName: [identity_information, full_name]
  first: [identity_information, first]
  middle: [identity_information, middle]
  last: [identity_information, last]
physicalAddress:
  street: [contact_information, address, street]
  street2: [contact_information, address, street2]
  city: [contact_information, address, city]
  state: [contact_information, address, state]
  country: [contact_information, address, country]
  postalCode: [contact_information, address, postal_code]
veteranSocialSecurityNumber: [identity_information, ssn]
phoneNumber: [contact_information, us_phone]
emailAddress: [contact_information, email]
```

I know we have mailingAddress but the backend isn't set up at all to handle two sets of addresses so let's just get this working and we can work on that later if need be
