### ISSUE TITLE
Define Test Pod in vets-api dev wrapper Chart

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#89534]
# Description
In order for a helm test invocation to an internal resource to function correctly we need a test pod to be defined in the parent `vets-api` helm chart. By defining the test pod in the dev wrapper chart, we can be sure that every EKS cluster that contains a `vets-api` resource also contains a test pod.

## Example
```
apiVersion: v1
kind: Pod
metadata:
  name: "vets-api-postman-test"
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: postman
      image: vets-api-postman:1.1.1
      command: ['postman-exec']
  restartPolicy: Never
```

# Acceptance Criteria
- [x] `vets-api` dev wrapper helm chart contains a definition for a test pod that uses the postman/newman container
