### ISSUE TITLE
Dangerfile errors on 'bad' pdf

### ISSUE THREAD

**Issue by scottsdevelopment** [department-of-veterans-affairs/va.gov-team#89532]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/17573
Job Logs: https://github.com/department-of-veterans-affairs/vets-api/actions/runs/10151061034/job/28069543213?pr=17573

When working on this PR the Danger was throwing an error likely due to the format of the files being renamed, I tried including a fix to use `--no-renames` or some kind of `-M` flag but I was not able to find a quick solution. More investigation would be needed. 

## Error and warning exceptions

The `Dangerfile` is executing a git command such as `git diff origin/master...feature/pension-modules-3 --numstat -w --ignore-blank-lines -- . `

```
57      4       lib/pdf_fill/filler.rb
0       0       {spec/fixtures/pdf_fill/21P-527EZ => modules/pensions/spec/pdf_fill/fixtures}/merge_fields.json
14      4       {spec/lib => modules/pensions/spec}/pdf_fill/forms/va21p527ez_spec.rb
```
this outputs something like the following above, and the problem is the current script seems to fail when there is a renamed file due to the error message I interpreted.

When looking at the CI,

```
bundle exec danger --head=e99c59f076e33f82f1154471251c5f8f9d177836 --base=8450d5421d0611fdda1f4401f44d10b27d57a5fa --verbose
  shell: /usr/bin/bash -e {0}
  env:
    BUNDLE_ENTERPRISE__CONTRIBSYS__COM: ***
    DANGER_GITHUB_API_TOKEN: ***
sh: 1: cannot create modules/pensions/lib}/pdf_fill/forms/va21p527ez.rb: Directory nonexistent
bundler: failed to load command: danger (/home/runner/work/vets-api/vets-api/vendor/bundle/ruby/[3](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/10150900965/job/28069030882?pr=17573#step:4:3).3.0/bin/danger)
```

It seems to be pointing to the renamed file line due the inclusion of the `}` character in how it is parsing this and crashing because of not finding an invalid directory.
