### ISSUE TITLE
[BE] Handle 403s from LoROTA `data` call

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#89625]
In some instances, we get a 403 'data has expired' response from LoROTA `data` call, which is not currently mapped in vets-api. This ends up throwing the exception and logging an error in sentry.

```
Unmapped VA900 (Backend Response: { status: 403, message: {"error":"data has expired"}) } : {:i18n_exception_hint=>"Add the following to exceptions.en.yml
LOROTA-API_403:
  code: 'LOROTA-API_403'
  detail: ''
  status: <http status code you want rendered (400, 422, etc)>
  source: ~
"}
```

parent ticket: #89085
