### ISSUE TITLE
[COGNITION] Official banner dropdown misalignment

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#9061]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

While testing the accessibility of the site, one test is to set the browser width to 1280px and zoom in on the page to 400%. When that is done, the dropdown link inside the "An official website of the United States government" banner at the top of the page gets misaligned.

![Screen Shot 2020-05-11 at 9 49 26 AM](https://user-images.githubusercontent.com/136959/81846117-37224280-9517-11ea-8794-1d684bf601e0.png)

File source: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/includes/usa-website-header.html

## Acceptance Criteria

- [ ] "Here's how you know" link is inline with text
- [ ] Determine if entire banner should remain clickable (as it is now), or just the link

## Environment

* Operating System: All
* Browser: All
* Screenreading device: N/A
* Server destination: All

## Steps to Recreate

1. Go to staging.va.gov
1. Resize the browser window to be 1280px wide (open the dev tools to see the current size while resizing)
1. Zoom the browser to 400%
1. Examine the banner at the top of the page.

## Possible Fixes (optional)

The following CSS will fix it, but only the link is clickable (vs the entire banner before the below css is applied)

```css
@media screen and (max-width: 481px) {
  .usa-banner-button {
    display: inline;
    width: auto;
    height: auto;
    position: static;
    padding: 0;
    vertical-align: middle;
  }
}
```

## WCAG or Vendor Guidance (optional)

Unknown
