### ISSUE TITLE
Update config to use multiple AZs when in production

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#90699]
## Description
The infrastructure the API team is currently using requires us to send 2 "subscription key" header if the environment is production, and only 1 subscription key header if in lower environments. This is due to load balancing on their side - on the chance that our request gets load balanced to one instance or the other, we must provide both subscription key headers.

See: https://dsva.slack.com/archives/C05UTPZRZFY/p1723583609505639

**Recommend option 1 (below) for "good enough" reasons and speed of change.**

There are multiple options:
1. We copy [what the check in team has](https://github.com/department-of-veterans-affairs/vets-api/blob/08626f65d028adf525c8038d6f1777272a35bced/modules/check_in/app/services/travel_claim/client.rb#L156), which is easy but potentially difficult or at least a little hacky to test locally
2. We set up a config structure that lets us avoid `if prod` checks in our code and lets us test "better", but will have an impact on multiple files - client.rb, settings.yml, 6 infra-repo files, and any test files. Thinking a config structure like:
```yml
// For non prod
travel_pay:
  // ...
  subscription_keys:
    - 123123123 // default subscription key

// For prod
travel_pay:
  // ...
  subscription_keys:
    e: 123123123
    s: 456456456
```
3. Others I haven't considered

## Acceptance Criteria
- [ ] Code accepts 2 subscription key headers when in production env
- [ ] Tests added and pass locally
- [ ] Staging still works

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic**
