### ISSUE TITLE
EVSS PCIU Migration: Forms review

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#90980]
## User Story
As the developers responsible for backend work on the EVSS PCIU migration,
We need VFS teams to test their forms,
So that we can validate the migration of PCIU from the current EVSS environment.

## Issue Description
The table below was created by looking at the [form_profile_mappings](https://github.com/department-of-veterans-affairs/vets-api/tree/master/config/form_profile_mappings) in vets-api and finding all instances of forms using `contact_information`. Almost all forms (33 of them) use `contact_information` for some of their fields, but there is considerable overlap, so we don't need to test all 33 of the forms. Two forms cover all fields, `10-7959` and `21-0966` (but I'm also sharing an alternative to `10-7959` in case that one one is easier to test).

**`10-7959`**
```yaml
    street: [contact_information, address, street]
    street2: [contact_information, address, street2]
    city: [contact_information, address, city]
    state: [contact_information, address, state]
    country: [contact_information, address, country]
    postalCode: [contact_information, address, postal_code]
  phone_number: [contact_information, us_phone]
  email_address: [contact_information, email]
```
**`28-8832` (aka `27-8832`?) (alternate to the one above. Either can be used to test these fields)**
```yaml
claimantAddress:
  country: [contact_information, address, country]
  street: [contact_information, address, street]
  street2: [contact_information, address, street2]
  city: [contact_information, address, city]
  state: [contact_information, address, state]
  postalCode: [contact_information, address, postal_code]
claimantPhoneNumber: [contact_information, us_phone]
claimantEmailAddress: [contact_information, email]
```
**Form `21-0966` covers the remaining fields**
```yaml
  mobilePhone: [contact_information, mobile_phone]
  homePhone: [contact_information, home_phone]
  email: [contact_information, email]
  address: [contact_information, address]
```
| Form     | GitHub Team                           | Contacted | Slack channel |
| -------------- | ------------------------------------ | ------------------ | ---- |
| `10-7959c`       | [IVC CHAMPVA](https://github.com/orgs/department-of-veterans-affairs/teams/champva-engineering)                            | | #ivc-forms |
| `28-8832`  (aka `27-8832`?)       | [benefits-non-disability](https://github.com/orgs/department-of-veterans-affairs/teams/benefits-non-disability)            | | #benefits-non-disability |
| `21-0966`| [platform-va-product-forms](https://github.com/orgs/department-of-veterans-affairs/teams/platform-va-product-forms) | | #veteran-facing-forms |

Form numbers can be searched here: https://www.va.gov/find-forms

## Tasks
- [x]  Contact teams to test prefill functionality for their forms (we're specifically interested in the contact info fields being prefilled).
- [x] Communicate that the flipper for this functionality needs to be on in Staging for accurate testing (test the flipper on/off scenarios for a user and make sure the data is prefilled in each scenario).
- [x] Put instructions for testing locally and in staging

## Success Metrics
Two forms are tested.

## Acceptance Criteria
- [x] All contact information on forms `21-0966` and either `28-8832` or `10-7959` was successfully prefilled using a test user in Staging.
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
