### ISSUE TITLE
Discovery: Capture and report build metrics in GitHub Actions

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#9556]
## Overview 
- It's difficult to see build metrics in aggregate for VA.gov needed to identify trends or problems 
- Being able to track build duration and failure rates will allow us to optimize the Platform for scalability, track the success of iterations, and get ahead of significant issues (such as 90 minute pipelines) before they happen

## Tasks 

- Evaluate how we can get build metrics from GitHub Actions
- Identify useful metrics that we should capture and report on 
   - Build duration in vets-website and content-build
   - Full pipeline duration in vets-website and content-build
   - Fully deploy success/failure rate in vets-website and content-build
   - Success/failure rate of content releases
   - Other pipeline steps? Anything else? 
- Determine where we should display these metrics

**Comment by timwright12** [comment]
This doesn't complete this ticket, but we do now have build timestamps available for each step: https://www.va.gov/metalsmith-build-data.json

**Comment by meganhkelley** [comment]
Notes from May 2020 (when this ticket was about pulling metrics from CircleCI) — some of these notes and tools may/may not apply now 

> Build times by task could be reported into prometheus and displayed through grafana. We could push this information into a Google sheet to validate that the information / views are useful 
> Recent build failures could be displayed in the FE ops dashboard. Getting useful failures here may require some iteration on what build failures get displayed and may require some improvements to logging.

**Comment by alexandec** [comment]
### Potential approaches

#### Scribd Datadog action
https://github.com/scribd/github-action-datadog-reporting

This action sends Datadog the total workflow duration, and job duration for each job in the workflow. Job status for each job is also included. The downside of this approach is that the action can't be extended to send additional metrics. But the upside is that configuration is very simple.

This action must run after all other jobs for proper tracking. It requires a Datadog API key and a GitHub (Octokit) token. It fetches the relevant metrics from the GitHub API, formats them correctly, and sends the metrics to Datadog.

Example workflow with action configuration:

```
name: My Workflow
jobs:
  job1: ...
  job2: ...
  metrics:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    name: Datadog reports
    if: ${{ always() }}
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - uses: scribd/github-action-datadog-reporting@v1
        with:
          datadog-metric-prefix: 'content_build'
          metrics-type: 'job_metrics'
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          OCTOKIT_TOKEN: ${{ secrets.OCTOKIT_TOKEN }}
```

The `datadog-metric-prefix: 'content_build'` parameter causes workflow and job metrics to be prefixed, giving them a unique namespace in Datadog. For example, `content_build.job_duration` would be distinct from `vets_website.job_duration`.

The `metrics-type: 'job_metrics'` parameter indicates that the action should send job and workflow durations to Datadog.

There's an optional `tagged-branches` parameter which allows you to specify specific branches you want tagged, making it easier to track them in Datadog. For example, `tagged-branches: ['master']` would cause the master branch to be tagged as "master" and all other branches to be tagged as "other".

Here's an example of a job metric as it would be sent to Datadog:

```
Metric name: content_build.job_duration
Metric value: 422.0
Tags: 
{
  workflow: "Daily Production Deploy",
  project: "department-of-veterans-affairs/content-build",
  status: "success",
  name: "Build",
}
```

#### GHA Datadog action
https://github.com/marketplace/actions/datadog-action

This action sends arbitrary events to Datadog. You can send multiple metrics per event. This action is more configurable than the Scribd one above, but also more complex to configure. It requires Datadog API key.

Since this action does not handle fetching metrics from GHA, we'd have to implement that ourselves. To avoid creating a separate script, we might be able to use the `http-request-action` to make the API request. Then we'd have to parse the response to get the duration. Maybe we could use [fromJSON()](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson) for parsing. However, it's possible that the difficulty of parsing and reassembling the metrics would be too much to accomplish with GHA config and we'd have to create a separate script to do it. See below for more details on fetching metrics from GitHub.

Example step to send a metric:

```
- name: Build count
  uses: masci/datadog@v1
  with:
    api-key: ${{ secrets.DATADOG_API_KEY }}
    metrics: |
      - type: "count"
        name: "test.runs.count"
        value: 1.0
        host: ${{ github.repository_owner }}
        tags:
          - "project:${{ github.repository }}"
          - "branch:${{ github.head_ref }}"
```

#### Custom script to send metrics to Datadog
https://github.com/department-of-veterans-affairs/devops/pull/9086/

The CMS team created a custom bash script to send GraphQL query times to Prometheus. It uses curl to fetch metrics from two different Jenkins endpoints. Then it uses curl to send the metrics to Prometheus. The script is striggered by a groovy seed job which runs every 5 minutes.

Here's a shortened excerpt from the custom script:

```
# Get GraphQL Query Information
BUILD_LOG=`curl --silent --request POST --location \
    --cookie $COOKIE_JAR/cookies.txt \
    --user $USERNAME:$TOKEN \
    --header "Jenkins-Crumb: $jenkinsCrumb" \
    http://jenkins.vfs.va.gov/job/builds/job/vets-website-content-vagovprod/lastSuccessfulBuild/consoleText`

BUILD_TIME=`echo $BUILD_LOG | grep -oP 'Done in \d+\.\d+s' | grep -oP '\d+\.\d+' | tail -1` # seconds
echo "BUILD_TIME $BUILD_TIME"  >> $PUSH_GATEWAY_DIR/push_gateway.txt

# Send to Prometheus
cat $PUSH_GATEWAY_DIR/push_gateway.txt | curl --silent --data-binary @- ${pushGatewayURL}
```

We could adopt a similar approach, except we'd write a script to fetch metrics from the GHA API, then send the metrics to Datadog. I don't think a cron trigger would be required since we could run the script as part of the GHA workflow. This is the most configurable option but also requires the most work on our part. See below for more information about fetching metrics from GitHub.

#### Actions monitoring from Datadog
https://dsva.slack.com/archives/CU1E4CX9U/p1630687333001300

Apparently Datadog will be releasing an API integration for GHA in less than a month. It's not yet clear whether the integration will include duration metrics. If it does, it might be the preferred solution since it should be the simplest.

### Fetching GitHub metrics
If we choose to create a custom script, we'll need to fetch timing and status metrics ourselves. GitHub has a [workflow API](https://docs.github.com/en/rest/reference/actions#get-workflow-run-usage) we can use to get workflow, job, and step information. For example, this request:

```
https://api.github.com/repos/department-of-veterans-affairs/content-build/actions/runs/1195786076/jobs
```

provides a list of all the jobs in the workflow. Within each job it shows timing and status, then lists all the steps in the job, and the status and timing of each step. This provides us with a good level of detail for transmission to Datadog. Of course the response data has to be trimmed down and formatted first.

Here's an abbreviated look at the response:

```
{
  "total_count": 16,
  "jobs": [
    ...
    {
      "id": 3500310034,
      "status": "completed",
      "conclusion": "success",
      "started_at": "2021-09-02T21:16:01Z",
      "completed_at": "2021-09-02T21:17:23Z",
      "name": "Unit Tests",
      "steps": [
        ...
        {
          "name": "Run unit tests",
          "status": "completed",
          "conclusion": "success",
          "number": 8,
          "started_at": "2021-09-02T21:16:23.000Z",
          "completed_at": "2021-09-02T21:17:22.000Z"
        },
        {
          "name": "Generate coverage report by app",
          "status": "completed",
          "conclusion": "success",
          "number": 9,
          "started_at": "2021-09-02T21:17:22.000Z",
          "completed_at": "2021-09-02T21:17:22.000Z"
        },
        ...
      ],
    },
    ...
  ]
}
```

Note that this data is paginated, so fetching multiple pages may be required.
