### ISSUE TITLE
Create documentation in runbook for Program Management

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-team#96334]
As a program manager, I know how to configure my project such that I can see all sub-issues by epic/initiative on a roadmap, even when the sub issues are managed in different projects, so that I can track the overall progress of my program. 

**Acceptance Criteria**
-  Project configuration instructions are added to the GHP Migration Runbook that define:
- - How to create a workflow that when a parent is added to an issue, the issue is then auto-added to the same project as the parent
- - How to create a github action that when the status of an issue is changed in one project, it is also auto-changed in all other projects the issue lives in
-  - How to configure and turn on the workflow to auto-archive closed issues older than X months

**Comment by msbtterswrth** [comment]
For posterity, I created a new slack canvas that contains the following content.

Github Actions for GH ProjectsAs you migrate to GitHub Projects, some of ZenHub’s automated features may need to be recreated with GitHub Actions. This guide outlines basic steps for setting up GitHub Actions to support common workflows, such as updating statuses, automating labels, and tracking dependencies. These steps are typically best suited for engineers to execute.

1. Getting Started with GitHub Actions
GitHub Actions are workflows triggered by specific events in your repository, such as issues being opened, comments added, or pull requests merged. You can create custom actions or use pre-built actions from the GitHub Marketplace.

* Location: Actions are stored in a .github/workflows/ folder in your repository.
* File Format: Each action is defined in a .yml file.
* Events: Common events include issue_opened, issue_labeled, issue_closed, pull_request, and push.


2. Setting Up Secrets
Many GitHub Actions require the GITHUB_TOKEN, a secure token automatically provided by GitHub to allow the action to authenticate and interact with your repository. Secrets can be added in your repository settings under Settings > Secrets and variables > Actions. Your lead engineer can help set these up.

3. Common GitHub Actions to Replace ZenHub Features
Below are examples of useful GitHub Actions that can replace common ZenHub automations.

Action 1: Automatic Status Updates
Automatically update issue statuses when certain events occur (e.g., when a pull request is merged). 

```
name: Update Issue Status

on:
  pull_request:
    types: [closed]

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Update Issue Status to "Done"
        uses: actions-ecosystem/action-update-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          comment: "Status: Done"

```

Action 2: Automated Labeling
Automatically add labels to issues based on the content of their titles or descriptions, useful for labeling bugs, enhancements, or epics.

```
name: Auto-label Issues

on:
  issues:
    types: [opened, edited]

jobs:
  label-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Add Bug Label
        if: contains(github.event.issue.title, 'bug')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "bug"

```

Action 3: Assign Issues Based on Labels
Automatically assign an issue to a specific user based on the label applied to it (e.g., assigning all “bug” issues to a specific team member).
```

name: Auto-assign on Label

on:
  issues:
    types: [labeled]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign to Developer for Bug
        if: contains(github.event.label.name, 'bug')
        uses: actions-ecosystem/action-assign-issue@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: "username"
```


Action 4: Tracking Dependencies
Automatically link issues as dependencies, mimicking ZenHub’s dependency tracking. Use custom issue comments or labels to indicate a dependency.
```

name: Track Dependencies

on:
  issues:
    types: [opened, edited]

jobs:
  add-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Add Dependency Label
        if: contains(github.event.issue.body, '#dependent-on')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "dependency"
```


Action 5: Program Management
Automatically adds an issue to a second project (like a program, for example) whenever a new issue is created in your repository. This action listens for the issues event and adds the issue to a specified project if it meets certain conditions. 

Prerequisites

* You’ll need the project ID of the destination project where you want the issue to be added. You can find this by inspecting the project URL or by using GitHub’s API to retrieve the project ID.
* Permissions: Make sure the GitHub Actions token (GITHUB_TOKEN) has the necessary permissions to add issues to projects.
```

name: Add Issue to Second Project

on:
  issues:
    types: [opened]

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add Issue to Secondary Project
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const projectId = 'YOUR_SECOND_PROJECT_ID';  // Replace with your target project ID

            const issue = context.payload.issue;
            
            const addProjectItem = await github.graphql(`
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `, {
              projectId: projectId,
              contentId: issue.node_id
            });

            console.log(`Issue #${issue.number} added to project with item ID: ${addProjectItem.addProjectV2ItemById.item.id}`);
```

Action 6: Syncing Status
Automatically syncs the status field of an issue across two GitHub Projects whenever the status changes in one of them. This action will detect changes to the status field in one project and update the corresponding status field in the second project. 

Prerequisites

* Project IDs and Field IDs for the "status" field in both projects. You’ll need to get these using GitHub’s API or inspect the project settings.
* Permissions: The GitHub Actions token (GITHUB_TOKEN) should have permission to access and modify fields in both projects.
```

name: Sync Status Across Projects

on:
  issues:
    types: [edited, labeled, unlabeled, closed, reopened]

jobs:
  sync-status:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Status Field
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const sourceProjectId = 'YOUR_SOURCE_PROJECT_ID';  // Replace with the source project ID
            const targetProjectId = 'YOUR_TARGET_PROJECT_ID';  // Replace with the target project ID
            const statusFieldId = 'YOUR_STATUS_FIELD_ID';      // Replace with the status field ID for both projects

            // Fetch the current issue status from the source project
            const issueNodeId = context.payload.issue.node_id;

            // Fetch the status field value in the source project
            const { resource } = await github.graphql(`
              query($projectId: ID!, $issueId: ID!) {
                node(id: $issueId) {
                  ... on Issue {
                    projectItems(first: 10) {
                      nodes {
                        fieldValues(first: 10) {
                          nodes {
                            projectField {
                              id
                            }
                            value
                          }
                        }
                      }
                    }
                  }
                }
              }
            `, {
              projectId: sourceProjectId,
              issueId: issueNodeId
            });

            // Extract the current status from the source project
            const currentStatus = resource.node.projectItems.nodes.find(item => item.projectField.id === statusFieldId)?.value;

            if (!currentStatus) {
              console.log("No status field found or status has not changed.");
              return;
            }

            // Update the status in the target project
            await github.graphql(`
              mutation($projectId: ID!, $contentId: ID!, $status: String!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId,
                  itemId: $contentId,
                  fieldId: "${statusFieldId}",
                  value: $status
                }) {
                  projectV2Item {
                    id
                  }
                }
              }
            `, {
              projectId: targetProjectId,
              contentId: issueNodeId,
              status: currentStatus
            });

            console.log(`Status synced successfully to target project for issue ID: ${issueNodeId}`);

```


4. Testing and Debugging Actions

* View Action Logs: Each GitHub Action generates logs that you can view in the Actions tab to troubleshoot errors.
* Dry Runs: Test your actions with dry runs by creating test issues and observing their behavior before applying them to production.


5. Advanced Automation Ideas

* Automate Pull Request Merging: Automatically merge pull requests that meet specific criteria.
* Cross-Project Notifications: Send notifications to Slack or email when critical issues are updated or closed.
* Daily Summaries: Generate daily or weekly reports of open issues, closed tasks, or unassigned items.
