### ISSUE TITLE
[Burial Module] Create :burial_module_enabled Flipper

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#98411]
Add a flipper `:burial_module_enabled` to allow us to easily switch between our current setup and the new module

- Update `features.yml`:
```
burial_module_enabled:
  actor_type: user
  description: Enables new Burial module
  enable_in_development: true
```
- Update FE to add Flipper around path i.e. `Flipper.enabled?(:burial_module_enabled)`
