### ISSUE TITLE
Test form prefills for the 10182 form (Benefits Decision Reviews Team)

### ISSUE THREAD

**Issue by AshleyGuerrant** [department-of-veterans-affairs/va.gov-team#99077]
For the PCIU migration, the Platform Product Team changed the base class pre-fill to call VA Profile. This impacts the prefill fields for form 10182 listed below:
```yaml
    veteran:
      address:
        addressLine1: [contact_information, address, street]
        addressLine2: [contact_information, address, street2]
        city: [contact_information, address, city]
        stateCode: [contact_information, address, state]
        zipCode5: [contact_information, address, postal_code]
        countryName: [contact_information, address, country]
      emailAddressText: [contact_information, email]
```
### Tasks
- [ ] Turn on flipper `remove_pciu` [**IN STAGING**](https://staging-api.va.gov/flipper/features)
- [ ] Test prefill for form 10182 in staging.
- [ ] If testing is successful, comment and close this issue.
- [ ] If issues are found (or if there are questions) reach out in [#pciu-migration-testing](https://dsva.slack.com/archives/C085A9JCB1B)
