### ISSUE TITLE
Test form prefills for Form 28-8832 (Benefits Non-disability Team)

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#99070]
For the PCIU migration, the Platform Product Team changed the base class pre-fill to call VA Profile. This impacts all of the prefill fields for form 28-8832 (listed below)
```yaml
claimantAddress:
  country: [contact_information, address, country]
  street: [contact_information, address, street]
  street2: [contact_information, address, street2]
  city: [contact_information, address, city]
  state: [contact_information, address, state]
  postalCode: [contact_information, address, postal_code]
claimantPhoneNumber: [contact_information, us_phone]
claimantEmailAddress: [contact_information, email]
```
### Tasks
- [x] Turn on flipper `remove_pciu` [**IN STAGING**](https://staging-api.va.gov/flipper/features)
- [x] Test prefill for form 28-8832 in staging.
- [x] If testing is successful, comment and close this issue.
- [ ] If issues are found (or if there are questions) reach out in [#pciu-migration-testing](https://dsva.slack.com/archives/C085A9JCB1B)
