### ISSUE TITLE
Test form prefills for Form 10-7959c (IVC CHAMPVA Team)

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#99072]
For the PCIU migration, the Platform Product Team changed the base class pre-fill to call VA Profile. This impacts the prefill fields for form 10-7959c listed below:
```yaml
    street: [contact_information, address, street]
    street2: [contact_information, address, street2]
    city: [contact_information, address, city]
    state: [contact_information, address, state]
    country: [contact_information, address, country]
    postalCode: [contact_information, address, postal_code]
  phone_number: [contact_information, us_phone]
  email_address: [contact_information, email]
```
### Tasks
- [ ] Turn on flipper `remove_pciu` [**IN STAGING**](https://staging-api.va.gov/flipper/features)
- [ ] Test prefill for form 10-7959c in staging.
- [ ] If testing is successful, comment and close this issue.
- [ ] If issues are found (or if there are questions) reach out in [#pciu-migration-testing](https://dsva.slack.com/archives/C085A9JCB1B)
