### ISSUE TITLE
Test form prefills for Form 21-0966 (VA Product Forms Team)

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#99075]
For the PCIU migration, the Platform Product Team changed the base class pre-fill to call VA Profile. This impacts the prefill (and non-prefil) fields for form 21-0966 listed below:
```yaml
    veteran:
      address:
        zipCode5: [contact_information, address, postal_code]
      emailAddressText: [contact_information, email]
nonPrefill:
  veteranAddress:
    street: [contact_information, address, street]
    street2: [contact_information, address, street2]
    street3: [street3]
    city: [contact_information, address, city]
    state: [contact_information, address, state]
    country: [contact_information, address, country]
    postalCode: [contact_information, address, postal_code]
```

### Tasks
- [ ] Turn on flipper `remove_pciu` [**IN STAGING**](https://staging-api.va.gov/flipper/features)
- [x] Test prefill for form 21-0966 in staging.
- [x] Test the `nonPrefill` fields listed above, if possible. 
- [x] If testing is successful, comment and close this issue.
- [ ] If issues are found (or if there are questions) reach out in [#pciu-migration-testing](https://dsva.slack.com/archives/C085A9JCB1B)
